### ISSUE TITLE
Should be able to change the "Display Order" for Product Images by drag and drop

### ISSUE THREAD

**Issue by Farshidgolkarihagh** [nopSolutions/nopCommerce#7246] opened 2024-06-20 20:57 UTC
nopCommerce version: 4.60.3

Steps to reproduce the problem: Most modern application allow for dragging images in order to change the order for which they appear. It would be very nice to allow for this.

**Comment by glhays** [comment] 2024-06-20 22:59
It is also very nice to order them by the way it currently is.

**Comment by RomanovM** [comment] 2024-12-11 13:05
Duplicate of #656

**Closed by RomanovM** 2024-12-11 13:05 UTC
Labels: discussion / investigation
