### ISSUE TITLE
New install fail because missing plugin file

### ISSUE THREAD

**Issue by AHComp** [nopSolutions/nopCommerce#6178] opened 2022-03-14 11:49 UTC
nopCommerce version: Current development

Steps to reproduce the problem: 

        public virtual bool LoadPluginInfo()
        {
            //check whether plugins info file exists
            var filePath = _fileProvider.MapPath(NopPluginDefaults.PluginsInfoFilePath);
            if (!_fileProvider.FileExists(filePath))
            {
                //file doesn't exist, so try to get only installed plugin names from the obsolete file
                _installedPluginNames.AddRange(GetObsoleteInstalledPluginNames());

                //and save info into a new file if need
                if (_installedPluginNames.Any())
                    Save();
            }

            //try to get plugin info from the JSON file
            //var text = _fileProvider.FileExists(filePath)
            //    ? _fileProvider.ReadAllText(filePath, Encoding.UTF8)
            //    : string.Empty;

            //if (string.IsNullOrEmpty(text) || !DeserializePluginInfo(text))
            //    return false;

If i start the nop.web with new installation it happens.

If i comment out the last blocks it works fine, why you check the creating of the new file if not exist and throw a exception then ?

**Comment by RomanovM** [comment] 2022-03-14 12:18
Thanks. Duplicate of #6163

**Closed** 2022-03-14 12:19 UTC
