### ISSUE TITLE
Create customer form not having required field Aesthetic symbol

### ISSUE THREAD

**Issue by sangeet-shah** [nopSolutions/nopCommerce#7167] opened 2024-05-02 10:03 UTC
nopCommerce version: 4.7

Steps to reproduce the problem: 

![image](https://github.com/nopSolutions/nopCommerce/assets/75615233/c8c01bcf-5aac-4110-8ebf-dbb56e397e71)

**Comment by RomanovM** [comment] 2024-05-02 10:06
Duplicate of #6244

**Closed** 2024-05-02 10:06 UTC
