### ISSUE TITLE
Bug: "Load all localized properties on startup" and save and contiune

### ISSUE THREAD

**Issue by hrvoje-grabusic** [nopSolutions/nopCommerce#5932] opened 2021-11-03 13:52 UTC
nopCommerce version: 
verzija nopCommerce
4.40.4
Operativni sustav
Microsoft Windows NT 6.3.9600.0
informacije ASP.NET
.NET 5.0.11

Steps to reproduce the problem: 
1. Enable "Load all localized properties on startup"
2. Setup 2 languages
3. In product enter some text in both language tabs and click Save and continue edit

After save and continue the page will refresh but text will not show in all language tabs.
Everything is saved in the database and after another refresh it will show everything,

Looks like a caching issue. Save not clearing the cache ?

**Comment by kava81** [comment] 2021-11-03 13:56
I have the same problem

**Comment by RomanovM** [comment] 2021-11-05 12:25
Duplicate of #5700

**Closed by RomanovM** 2021-11-05 12:25 UTC
