### ISSUE TITLE
4.40-beta throws mysql exception 

### ISSUE THREAD

**Issue by nextfool** [nopSolutions/nopCommerce#5492] opened 2021-03-04 05:56 UTC
nopCommerce version: 4.40-beta
env:  ubuntu 20.04 + .net 5 sdk + mysql

Steps to reproduce the problem: 
1. fresh install, choose mysql as database, also install the sample data.
2. go to any of the categories in front site, e.g. http://localhost:5000/electronics and an exception throws.

exception details:

fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      MySql.Data.MySqlClient.MySqlException (0x80004005): Expression #1 of ORDER BY clause is not in SELECT list, references column '***hide-my-info***.sa.DisplayOrder' which is not in SELECT list; this is incompatible with DISTINCT
         at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
         at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
         at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
         at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
         at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
      --- End of stack trace from previous location ---
         at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
         at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
         at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
         at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
         at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
         at Nop.Services.Catalog.SpecificationAttributeService.<>c__DisplayClass38_0.<<GetFiltrableSpecificationAttributeOptionsByCategoryIdAsync>b__19>d.MoveNext() in /home/***hide-my-info***/src/Libraries/Nop.Services/Catalog/SpecificationAttributeService.cs:line 416
      --- End of stack trace from previous location ---
         at Nop.Core.Caching.MemoryCacheManager.GetAsync[T](CacheKey key, Func`1 acquire) in /home/***hide-my-info***/src/Libraries/Nop.Core/Caching/MemoryCacheManager.cs:line 112
         at Nop.Services.Catalog.SpecificationAttributeService.GetFiltrableSpecificationAttributeOptionsByCategoryIdAsync(Int32 categoryId) in /home/***hide-my-info***/src/Libraries/Nop.Services/Catalog/SpecificationAttributeService.cs:line 416
         at Nop.Web.Factories.CatalogModelFactory.PrepareCategoryProductsModelAsync(Category category, CatalogProductsCommand command) in /home/***hide-my-info***/src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs:line 952
         at Nop.Web.Factories.CatalogModelFactory.PrepareCategoryModelAsync(Category category, CatalogProductsCommand command) in /home/***hide-my-info***/src/Presentation/Nop.Web/Factories/CatalogModelFactory.cs:line 613
         at Nop.Web.Controllers.CatalogController.Category(Int32 categoryId, CatalogProductsCommand command) in /home/***hide-my-info***/src/Presentation/Nop.Web/Controllers/CatalogController.cs:line 118
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
         at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
         at WebMarkupMin.AspNetCore5.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
         at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 104
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in /home/***hide-my-info***/src/Libraries/Nop.Services/Authentication/AuthenticationMiddleware.cs:line 95
         at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
         at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in /home/***hide-my-info***/src/Libraries/Nop.Services/Installation/InstallUrlMiddleware.cs:line 52
         at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in /home/***hide-my-info***/src/Libraries/Nop.Services/Common/KeepAliveMiddleware.cs:line 49
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by skoshelev** [comment] 2021-03-04 06:09
Duplicate of #5425

**Closed by skoshelev** 2021-03-04 06:09 UTC

**Comment by nextfool** [comment] 2021-03-04 06:10
sorry I believe it's been  fixed in [https://github.com/nopSolutions/nopCommerce/issues/5425](url), so I am closing this.
