### ISSUE TITLE
Designing issue in child data-table on Shipment list page

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3739] opened 2019-04-30 08:24 UTC
nopCommerce version: 4.20 Beta

Steps to reproduce the problem: 
1. Go to Admin > Sales > Shipment
2. Open shipment items from shipment list table 
3. Check designs

Click [here](https://i.ibb.co/BZF8zdd/shipment-design.png) for see screen shot.

**Comment by RomanovM** [comment] 2019-04-30 08:32
Thanks. Duplicate of https://github.com/nopSolutions/nopCommerce/issues/3728

**Closed** 2019-04-30 08:32 UTC
