### ISSUE TITLE
Add more filters to search on list pages in the admin area 

### ISSUE THREAD

**Issue by tigran-avdalyan** [nopSolutions/nopCommerce#3305] opened 2018-09-19 14:47 UTC
Please see a list of suggestions in comments. Let's choose which ones we'll implement

**Comment by RomanovM** [comment] 2018-09-21 09:39
For example add filter by Published property on Category list page. What else?

**Comment by wize1** [comment] 2018-10-31 08:32
I agree. I think the problem is Kendoo controls, which has very limited functionality out of the box. DevExpress is lot better with its dynamic filter builder on grid view, plus they have normal filtering and sorting a lot better in first place. This been issue for many of our customers, that said that filtering and sorting on each of admin page is very limited and they would like to have each property of the entity managed been configurable in filter... So for example, if I want to search for combination of very order total price over 50$ and very customer name start with 'R' and order placed this month and its status is Pending, I can not do that currently.  Here is basically what im referring to:

https://demos.devexpress.com/MVCxGridViewDemos/Filtering/FilterBuilder

PS. I'm not in anyways advertising, devexpress or have any interest in it... I'm just wishing for better functionality in nopCommerce

**Comment by IAmThatStrange** [comment] 2018-11-08 15:09
Also add filters to the recurring payment list page.  Our clients will use recurring payments a lot for donations.  Being able to search via store, customer, dates, cycle periods and cycles remaining would be very nice.

**Comment by LubovKhokhlova** [comment] 2019-03-28 06:37
Possible filtering options for pages
1) product tags
by tag name
2) vendors
by email
3) News items
by title
4) Blog posts
by title
5) Countries
by Name
6) Warehouses
by Name
7) Plugins
by Name (local plugins)
by Author
8) Manage Categories and Manufacturers
by Published

**Comment by RomanovM** [comment] 2020-01-27 20:42
>We suggest you to provide filter by Author on nopCommerce plugin list page inside nopCommerce admin. This will give administrator an ability to filter plugins from a single author when there are several plugins installed in application.

Source: https://www.nopcommerce.com/boards/topic/74804/filter-by-author-on-nopcommerce-plugin-list

**Comment by szocco** [comment] 2020-02-17 18:19
Adding suggested filters:
Products by Product template
Sales>Orders by Customer Name (not billing name)

**Comment by mariannk** [comment] 2020-07-13 11:56
Add possibility to search by all Shipping methods on the Configure - Manual (Fixed or By Weight and By Total) page

**Comment by RomanovM** [comment] 2021-03-25 09:13
Search products by `ShowOnHomepage`. From https://www.nopcommerce.com/boards/topic/90152/nopcommerce-440-bug-fixes-and-improvements/page/9#283381

**Comment by RomanovM** [comment] 2021-08-12 06:20
Search customers by `LastActivityDate`. Suggested in https://www.nopcommerce.com/boards/topic/91632/search-for-active-customers-only

**Comment by AndreiMaz** [comment] 2021-11-13 01:49
Closing this. Decided to implement two new filters (separate work items) - https://github.com/nopSolutions/nopCommerce/issues/5905 and https://github.com/nopSolutions/nopCommerce/issues/5947

**Closed by AndreiMaz** 2021-11-13 01:49 UTC
Labels: on hold / maybe wont
