### ISSUE TITLE
 User registration email/Phone number not validated

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3573] opened 2019-03-05 04:42 UTC
nopCommerce version: 
Latest as on 05-Mar-2019
Steps to reproduce the problem: 

I am looking for registration process as given below.

User will register using Email or Phone number.

1) If user use email address to register (as username), then User will get email to validate, and after validation of email address user will get chance to fill other details.
2) If user use Phone number to register (as username), then User will get OTP to validate, and after validation of Phone number user will get chance to fill other details.
This is necessary rather must to avoid fake accounts.
I am sharing below website to understand what exactly I want.
https://www.flipkart.com/
Go to Login & Signup
 

![image](https://user-images.githubusercontent.com/31761152/53781488-0f0c7c00-3f2f-11e9-8635-3f5ff91e3611.png)

I tried setting "Registration method" to EmailValidation http://admin-demo.nopcommerce.com/Admin/Setting/CustomerUser

Still validation email has not been sent to user.

**### All I am novice to asp.net core, so it will take much time for me to implement it.

Can anyone expert take this on priority.**

**Comment by RomanovM** [comment] 2019-03-05 06:07
Duplicate of #2228

**Closed by RomanovM** 2019-03-05 06:07 UTC
