### ISSUE TITLE
RoxyFileman dies on interpreting an invalid image

### ISSUE THREAD

**Issue by GaborFarkas** [nopSolutions/nopCommerce#7045] opened 2024-01-28 14:32 UTC
nopCommerce version: 4.60.5

Steps to reproduce the problem: 
1. Create an empty file in wwwroot/images/uploaded
2. Rename it to resemble an image file (e.g. test.png)
3. Try to use an image uploader in any WYSIWYG

RoxyFileman will stop working when this happens, as the call on RoxyFilemanFileProvider.cs#396 returns null and the next line throws an exception.

Expected behavior:
- Do not list invalid images;
or
- List invalid images with some warning;
or
- Send a meaningful error message containing the problematic file's path relative to RoxyFileman root.

**Comment by RomanovM** [comment] 2024-03-22 05:56
Duplicate of #6932

**Closed** 2024-03-22 05:57 UTC
Labels: discussion / investigation
