### ISSUE TITLE
Product Image Rotates 90 Degrees After Upload in Admin Panel

### ISSUE THREAD

**Issue by CHIALINGTANG** [nopSolutions/nopCommerce#7461] opened 2024-12-16 15:56 UTC
nopCommerce Version: 4.6
nopCommerce Version: 4.7

Steps to reproduce the problem: 
https://www.nopcommerce.com/en/boards/topic/101241/product-thumbnail-image-rotates-90-degrees-after-upload-in-admin-panel

**Comment by skoshelev** [comment] 2024-12-16 18:46
Duplicate of https://github.com/nopSolutions/nopCommerce/issues/5818

**Closed by skoshelev** 2024-12-16 18:46 UTC
