### ISSUE TITLE
Deleting unused route

### ISSUE THREAD

**Issue by MohammadAnsari98** [nopSolutions/nopCommerce#6842] opened 2023-09-04 00:17 UTC
Hi can we delete this code from [RouteProvider.cs 
](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Presentation/Nop.Web/Infrastructure/RouteProvider.cs)
```
//error page
endpointRouteBuilder.MapControllerRoute(name: "Error",pattern: $"error",defaults: new { controller = "Common", action = "Error" });
```

since we don't have action **Error Action** inside Common controller
And going to /error redirects to pagenotfound

if we can delete i will be happy to create pr for that

**Comment by skoshelev** [comment] 2023-09-04 05:29
Duplicate of #6479

**Closed by skoshelev** 2023-09-04 05:29 UTC
