### ISSUE TITLE
Pickup.PickupInStore cannot installed   Beta 4.3

### ISSUE THREAD

**Issue by kwiksys** [nopSolutions/nopCommerce#4527] opened 2020-04-09 11:04 UTC
nopCommerce version: Beta 4.3

Steps to reproduce the problem: 
1) update 4.3  sql script
2) Local Login -> Select PickupInstore plugin and click Install button which result in plugin not installed.

See attached
![PickupInStore_1_9Apr2020](https://user-images.githubusercontent.com/31030124/78888799-f1e0a000-7a94-11ea-982a-02c1e9677bfa.jpg)

**Comment by DmitriyKulagin** [comment] 2020-04-10 13:44
@kwiksys Cannot reproduce the error. I tried removing the Pickup.PickupInStore plugin and then installing it through Admin -> Local plugins. But there are no errors. Describe in more detail how you removed the plugin? What database is the MySQL or MS SQL store deployed to?

**Comment by kwiksys** [comment] 2020-04-10 14:21
Hi,
I am attaching the database MS SQL . This is the database from version 4.20
Thanks
[DB_A54056_BPMPCI_4_9_2020.zip](https://github.com/nopSolutions/nopCommerce/files/4461903/DB_A54056_BPMPCI_4_9_2020.zip)

**Comment by DmitriyKulagin** [comment] 2020-04-13 14:51
We cannot reproduce the behavior you specified. On our examples, including the transitional base from version 4.20, everything works. If you find a sequence of actions that leads to a problem, you may reopen this task and complete the description. Now I am closing the task.

**Closed by DmitriyKulagin** 2020-04-13 14:51 UTC
Labels: discussion / investigation
