### ISSUE TITLE
kendoNumericTextBox issue with rtl languages

### ISSUE THREAD

**Issue by ertebatgharineh** [nopSolutions/nopCommerce#5736] opened 2021-06-16 08:39 UTC
nopCommerce version: 4.40.3

Steps to reproduce the problem:
1- create new Persain language with IR-fa culture.
2- go to every page that contains number box (like price filed or display order field)
3- go to browser console and check the errors
4- "uncaught syntaxerror invalid or unexpected token" for min value in kendoNumericTextBox function.
(if you set min value to 0 instead of int.minvalue this would be fixed)

**Comment by exileDev** [comment] 2021-06-16 11:58
@ertebatgharineh I couldn't reproduce this error on the clean installation. Are there any more conditions to reproduce the issue?

**Comment by exileDev** [comment] 2021-06-17 06:29
Closed #5736
For now, I'm closing it will reopen if needed.

**Closed by exileDev** 2021-06-17 06:29 UTC
Labels: discussion / investigation

**Comment by ampadashi** [comment] 2021-08-11 18:22
> nopCommerce version: 4.40.3
> 
> Steps to reproduce the problem:
> 1- create new Persain language with IR-fa culture.
> 2- go to every page that contains number box (like price filed or display order field)
> 3- go to browser console and check the errors
> 4- "uncaught syntaxerror invalid or unexpected token" for min value in kendoNumericTextBox function.
> (if you set min value to 0 instead of int.minvalue this would be fixed)

Check #5783. There's something wrong with the culture definitions in .NET Core. You can find the quick fix in this page but,  It's not the best solution.
