### ISSUE TITLE
Discount with Category in Nop4.0

### ISSUE THREAD

**Issue by nitin403** [nopSolutions/nopCommerce#3287] opened 2018-09-12 13:53 UTC
nopCommerce version: 

Steps to reproduce the problem: 
Install the NopCommerce 4.0
Install the "Customer spending over x.xx amount" plugin.
Create a new Discount with Discount Type "Assigned to Category" enter any coupon code.
Click on the save and continue button.
Go to the Requirement tab.
Select the "Customer spending over x.xx amount" from the dropdown and enter a value in the input box and click on the save button.
Add a category in the "Applied to categories" tab.
Go to the public store and then add a product from the above category and go to the cart page.
In Discount Box apply the discount code created earlier.

After applying the discount code it shows the 502 error page.
Nothing can be found the log for this.
Note: Public store don't works for this user after this. It always shows the 502 error page. 
Once the admin deletes the requirement record then only the public store starts working again.
Also had similar experience with other discount plugins.
Only the "Must be assigned to customer role" plugin seems to be working

**Comment by nitin403** [comment] 2018-09-14 14:29
Please add Order or OrderId in the DiscountRequirementValidationRequest so it become easy to validate the discount request against a Order and customer.
Also please add some documentation for developing discount plugin.

**Comment by DJBalogh** [comment] 2019-02-14 15:42
We're experiencing this issue on NOP 4.0 as well. 

Discount Type: Assigned to Products
Requirement: Customer spending over x.xx amount
Requirement: Customer is in customer role
Applied to products: Simple Product

The discount is 10% off when ordering $4950 or more of that particular product.
We even built our own plugin in house to replace Customer spending over x.xx amount and the site still went down with the 502 error.

**Comment by pantonis** [comment] 2019-03-07 05:53
Having the same problem on 4.10 as well. DId you find the cause?

**Comment by DmitriyKulagin** [comment] 2019-07-12 12:32
I just tried to repeat the error on the plugin for the current version 4.20 and this error did not happen. Please, look at the changes since this commit - https://github.com/nopSolutions/HadSpentAmount-discount-requiremement-plugin-for-nopcommerce/commit/8ee4926384c3dab45a671b0b29985cf7cc968ac8

**Closed by DmitriyKulagin** 2019-07-12 12:32 UTC
Labels: discussion / investigation
