### ISSUE TITLE
Lots of blank GUIDs in Customer table

### ISSUE THREAD

**Issue by rolandh** [nopSolutions/nopCommerce#2720] opened 2017-11-11 01:29 UTC
I have about 20 customers and about 1000 empty GUIDs in my customer table. I assume these are anonomous users that access the site? Do these ever get cleared as within a week I have a few thousand of them which looks like it may cause issues in the future, as there will surely be a few 100k of them in no time.

![image](https://user-images.githubusercontent.com/1109554/32684800-93a6f458-c6d7-11e7-9732-1b0035c09855.png)

![image](https://user-images.githubusercontent.com/1109554/32684809-d05f084a-c6d7-11e7-93bc-5ab4558d1c21.png)

**Comment by AndreiMaz** [comment] 2017-12-01 10:48
@rolandh We insert customers with some randon GUID. Which role these customers are mapped to?

**Comment by rolandh** [comment] 2017-12-02 06:31
They are mapped to guest (4). I assume each request from webbots or my external keep alives is creating a new "guest" customer?

When are these guest customers removed/cleaned up?

It is already up to Customer_Id = 45581, it appears it is clearing some of them but the ID keeps incrementing. I guess if it uses a long internally in the DB it would be many years before this became an issue.

**Comment by rolandh** [comment] 2017-12-05 02:11
We have our own plugin that has the following in the constructor:

IWorkContext workContext, ICustomerService customerService

Our API also has a KeepAlive function in there which is hit by anonymous clients. Would this be creating a new guest account each time?

The code below is all that executes when a guest logs in.

            var customer = _workContext.CurrentCustomer;
            var username = customer ?.Username?.ToLower().Trim();
            if (username.IsNullOrWhiteSpace()) return;

Is this code creating a guest account every single time the constructor to our plugin is created with a unauthorised user?

That doesn't seem correct, we have disabled guest accounts from purchasing or using the shopping cart, why is a guest account being created?

Also why is there no task to remove unused guest accounts?

I see that other users have been discussing this for quite some time.
https://www.nopcommerce.com/boards/t/37816/suggestion-improvement-on-generating-guest-customer.aspx

**Comment by rolandh** [comment] 2017-12-05 02:22
https://gist.github.com/rolandh/e3af826b8f5b082683b18c0bf56b1824

Can we add this code to WebWorkContext.cs ?

**Comment by AndreiMaz** [comment] 2017-12-08 12:46
@rolandh It's still not clear how to reproduce it (get empty GUIDs)

Regarding the code (CurrentRegisteredCustomer). No, we don't plan to use it (duplicate code). YOu can get CurrentCustomer and then just check whether he's registered

**Comment by rolandh** [comment] 2017-12-08 12:48
Customer generates a guest customer everytime to call it and no one is logged in. If you hit this function every second you end up with a new guest guid every second also.

**Comment by AndreiMaz** [comment] 2017-12-08 13:36
@rolandh right, but this task is about empty GUIDs. not about a lot of guest records (they periodically deleted)

**Comment by rolandh** [comment] 2017-12-09 03:10
The empty guid is mapoed to the guest role. Is this not the same thing?

**Comment by AndreiMaz** [comment] 2017-12-09 06:39
@rolandh Creation of new guest records for each new visitor (not for each request) is by design (they are deleted later), It's not the bug

But it's not possible to reproduce creation of guests with empty GUID. How can I do it out of the box? Please see this method (https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Customers/CustomerService.cs#L614), It clearly generates a new GUID for each guest

**Comment by AndreiMaz** [comment] 2017-12-25 19:00
Closing this task as it's not possible to reproduce out of the box.

**Closed by AndreiMaz** 2017-12-25 19:00 UTC
