### ISSUE TITLE
Limit some products to use/return reward points.

### ISSUE THREAD

**Issue by SharmaHarsh7** [nopSolutions/nopCommerce#2496] opened 2017-08-17 11:35 UTC
Hi,

It would be a very good enhancement if you can limit some products to add reward points on purchase.

Use Case:
If I create a gift card and send it to myself it will add the reward points to my account.
If I use that gift card on my purchase I will also be able to use those points again which I got while purchasing this Gift Card.
Let suppose, If I use this gift card to buy another gift card for my self and use those points it will again give me some more points without spending a single penny.

If I repeat this process N time it will give me enough points to buy anything free from the nop commerce based website.

I request you to please move this bug from the website.

You can add a checkbox on the product page itself, where we can mark it true if it is limited to use/return reward points.

**Comment by RomanovM** [comment] 2018-09-19 10:47
Duplicate of https://github.com/nopSolutions/nopCommerce/issues/2048

**Closed** 2018-09-19 10:47 UTC
Labels: functionality / feature
