### ISSUE TITLE
Meta description is not being HTML decoded when writing meta tags

### ISSUE THREAD

**Issue by nealculiner** [nopSolutions/nopCommerce#6938] opened 2023-12-04 14:37 UTC
nopCommerce version: 4.60.5

Steps to reproduce the problem: 

I have a product short description of: 

`Airline Pilot's Daily Aviation Logbook - the only complete CFR Part 117 app built by airline pilots for airline pilots`

When viewing the meta description it shows:

` <meta name="description" content="Airline Pilot&#x27;s Daily Aviation Logbook - the only complete CFR Part 117 app built by airline pilots for airline pilots" />`

I'm not sure what other SEO fields are affected but this is one of them as I'm building out my new store and noticed this.

**Comment by RomanovM** [comment] 2023-12-05 11:22
Duplicate of #5675

**Closed by RomanovM** 2023-12-05 11:22 UTC
