### ISSUE TITLE
Unable to load shared library 'libSkiaSharp' or one of its dependencies.

### ISSUE THREAD

**Issue by mkabab** [nopSolutions/nopCommerce#5639] opened 2021-04-23 15:28 UTC
nopCommerce version: 4.40.3

Steps to reproduce the problem: 
1. run on linux docker
2. complete installaction with sample data
3. go to admin panel
4. create new product
5. click on save and continue button

Exception:
An unhandled exception has occurred while executing the request.

System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory

at SkiaSharp.SkiaApi.sk_filestream_new(Void* path)

at SkiaSharp.SKFileStream.CreateNew(String path)

at SkiaSharp.SKFileStream..ctor(String path)

at SkiaSharp.SKFileStream.OpenStream(String path)

at SkiaSharp.SKCodec.Create(String filename, SKCodecResult& result)

at SkiaSharp.SKCodec.Create(String filename)

at SkiaSharp.SKBitmap.Decode(String filename)

at Nop.Services.Media.PictureService.GetDefaultPictureUrlAsync(Int32 targetSize, PictureType defaultPictureType, String storeLocation) in /src/Libraries/Nop.Services/Media/PictureService.cs:line 511

at Nop.Services.Media.PictureService.GetPictureUrlAsync(Picture picture, Int32 targetSize, Boolean showDefaultPicture, String storeLocation, PictureType defaultPictureType) in /src/Libraries/Nop.Services/Media/PictureService.cs:line 662

at Nop.Services.Media.PictureService.GetPictureUrlAsync(Int32 pictureId, Int32 targetSize, Boolean showDefaultPicture, String storeLocation, PictureType defaultPictureType) in /src/Libraries/Nop.Services/Media/PictureService.cs:line 545

at AspNetCore.Areas_Admin_Views_Shared_EditorTemplates_Picture.ExecuteAsync() in /app/Areas/Admin/Views/Shared/EditorTemplates/Picture.cshtml:line 27

at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)

at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)

at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)

at Microsoft.AspNetCore.Mvc.ViewFeatures.TemplateRenderer.Render()

at Microsoft.AspNetCore.Mvc.ViewFeatures.TemplateBuilder.Build()

at Nop.Web.Framework.TagHelpers.Admin.NopEditorTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output) in /src/Presentation/Nop.Web.Framework/TagHelpers/Admin/NopEditorTagHelper.cs:line 127

at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.RunAsync(TagHelperExecutionContext executionContext)

at AspNetCore.Areas_Admin_Views_Product__CreateOrUpdate_Pictures.ExecuteAsync() in /app/Areas/Admin/Views/Product/_CreateOrUpdate.Pictures.cshtml:line 121

at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)

at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)

at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)

at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)

at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)

at AspNetCore.Areas_Admin_Views_Product__CreateOrUpdate.<>c__DisplayClass45_0.<<ExecuteAsync>b__8>d.MoveNext() in /app/Areas/Admin/Views/Product/_CreateOrUpdate.cshtml:line 81

**Comment by mkabab** [comment] 2021-04-23 15:32
after restarting the container and refresh the edit product page, I have got this exception:
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKObject' threw an exception.

---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: Error loading shared library liblibSkiaSharp: No such file or directory

at SkiaSharp.SkiaApi.sk_version_get_milestone()

at SkiaSharp.SkiaSharpVersion.get_Native()

at SkiaSharp.SkiaSharpVersion.CheckNativeLibraryCompatible(Boolean throwIfIncompatible)

at SkiaSharp.SKObject..cctor()

--- End of inner exception stack trace ---

at SkiaSharp.SKObject.DeregisterHandle(IntPtr handle, SKObject instance)

at SkiaSharp.SKObject.set_Handle(IntPtr value)

at SkiaSharp.SKNativeObject.Dispose(Boolean disposing)

at SkiaSharp.SKObject.Dispose(Boolean disposing)

at SkiaSharp.SKFileStream.Dispose(Boolean disposing)

at SkiaSharp.SKNativeObject.Finalize()

**Comment by RomanovM** [comment] 2021-04-23 16:21
Duplicate of #5563

**Closed** 2021-04-23 16:21 UTC
