### ISSUE TITLE
Product attribute edit Predefined values display wrong popup  / Admin side

### ISSUE THREAD

**Issue by Ilyaspatel91-del** [nopSolutions/nopCommerce#5382] opened 2021-02-22 16:02 UTC
nopCommerce Version: 4.40 beta

Steps to reproduce the problem: 

1. Go /Admin/ProductAttributes/List
2. Click on Edit any product attribute 
3. Add any Predefined values
4. Edit the predefined values it will open popup and in that wrong values are exist 
5.  it will open the "ProductAttributeValueEditPopup" instead of "PredefinedProductAttributeValueEditPopup"

https://prnt.sc/103xcdm

**Comment by RomanovM** [comment] 2021-02-24 10:09
Thanks. Duplicate of #5360

**Closed** 2021-02-24 10:10 UTC
