### ISSUE TITLE
Saving pictures to a directory on disk to specific subdirectory

### ISSUE THREAD

**Issue by bambuca** [nopSolutions/nopCommerce#7380] opened 2024-10-24 13:58 UTC
nopCommerce version: 4.70

Currently, images (products, categories, etc.) are stored either in the database or on disk (according to "Media.Images.StoreInDB" setting).
If they are stored on disk, they are saved directly into the “images” directory. We have the application running in Docker, where we already have volumes set up for the directories “images/thumbs” and “images/uploaded”. Product images are currently stored in the SQL database.

We would like to store these images on the filesystem as well, but they will be stored directly in the “images” directory. We don’t want to create a volume for the entire “images” directory because it contains subdirectories like “flags”, which we don’t want to include in the volume.

As a possible solution, I thought of:
1.	Saving images into the subdirectory, fe “images/pictures”.
2.	Adding a setting in the configuration where the name of the subdirectory can be specified, e.g., "Media.Images.Subfolder", which by default would be empty (so backward compatible) but could be adjusted to the desired value.

**Comment by RomanovM** [comment] 2024-12-11 12:35
Duplicate of #5986

**Closed** 2024-12-11 12:35 UTC
Labels: discussion / investigation
