### ISSUE TITLE
Mobile verification while registering

### ISSUE THREAD

**Issue by mrnams** [nopSolutions/nopCommerce#3552] opened 2019-02-20 05:24 UTC
nopCommerce version: latest

Steps to reproduce the problem: 
Like amazon can we add mobile as mandatory to register,and make email optional.
Also we must enable two step security feature.
Also add OTP to verify delivery, i mean our site should send OTP to customer, customer must show/share OTP to verify customer.

**Comment by mrnams** [comment] 2019-02-20 05:24
Guys I feel its priority enhancement.

**Comment by RomanovM** [comment] 2019-02-20 07:03
Duplicate of https://github.com/nopSolutions/nopCommerce/issues/2228

**Closed** 2019-02-20 07:04 UTC

**Comment by mrnams** [comment] 2019-02-20 07:17
> 
> 
> Duplicate of #2228

Thanks for quick update.
But #2228 just gave link to 
https://firebase.google.com/docs/auth/web/phone-auth
Any plan to actual implementation of this?
