### ISSUE TITLE
Products that are still in stock are incorrectly unpublished

### ISSUE THREAD

**Issue by serialseb** [nopSolutions/nopCommerce#6040] opened 2021-12-19 15:28 UTC
nopCommerce version: 4.4 (bug-fix branch)

Steps to reproduce the problem: 
Add a product with a stock of 8. Set minimum stock to 0. Confirm an order, the product is unpublished, even though there are now 7 in stock.

I've isolated the problem to the `ApplyLowStockActivityAsync`, and my changes fix my issue.

Pull request to follow, feedback welcome, I may have misunderstood something.

**Comment by AndreiMaz** [comment] 2021-12-20 04:19
It's by design. Once a product is unpublished, you have to enable (publish) it back manually

**Comment by serialseb** [comment] 2021-12-24 05:03
I'm maybe not understanding correctly. I set the minimum stock to 0. I have 10 in stock. I sell 1. stock gets to 9. Product gets unpublished immediately, even though i still have 9. My understanding of the feature was that unpublish woudl happen when the current stock would reach my minimum stock befe action is taken. I understand that publish can happen automatically on cancellations and i took that into account in the PR associated, but I litterally have most of my products disappear from my catalog as soon as any is sold, however many are actually sold. Is this by design, or is 0 for minimum stock handled specifically, or am I completely misunderstanding the reasoning behind unpubkishing a product that still has 9 items in stocks in that warehouse?

**Comment by serialseb** [comment] 2021-12-24 05:04
@AndreiMaz I really want to understand what it is I'm doing wrong here, because the slight fix i made seems to solve the problem and only unpublish when we get to the minimum stock, and only republish when an order has been cancelled, so I'm extremely confused

**Comment by serialseb** [comment] 2021-12-24 05:05
Also an additional point here is that this method is called whenever an order is placed, not after an unpublishing, so we're talking about order -> order stock adjustment -> immediate unpublishing whatever the left over stock is.

**Comment by serialseb** [comment] 2021-12-24 05:09
Extra note, the code in `ProductServices.cs` is not actually invoking that method only when we are in low stock, but every time:

```

            if (product.ManageInventoryMethod == ManageInventoryMethod.ManageStock)
            {
                //update stock quantity
                if (product.UseMultipleWarehouses)
                {
                    //use multiple warehouses
                    if (quantityToChange < 0)
                        await ReserveInventoryAsync(product, quantityToChange);
                    else
                        await UnblockReservedInventoryAsync(product, quantityToChange);
                }
                else
                {
                    //do not use multiple warehouses
                    //simple inventory management
                    product.StockQuantity += quantityToChange;
                    await UpdateProductAsync(product);

                    //quantity change history
                    await AddStockQuantityHistoryEntryAsync(product, quantityToChange, product.StockQuantity, product.WarehouseId, message);
                }

                var totalStock = await GetTotalStockQuantityAsync(product);

                await ApplyLowStockActivityAsync(product, totalStock);
```

**Comment by skoshelev** [comment] 2021-12-24 09:56
Hi, @serialseb. I checked the logic of the ApplyLowStockActivityAsync method, and it is really broken in a part of the unpublish mechanism. The logic which you propose in [this commit](https://github.com/DooVillage/Nope/commit/0876c78c02c50a62d426282d04de01c6bd36c16a) is work, but I think it is a lite bit complicated to understand (as and our previous one). I made fixes to this problem, please lock on them, how do you think is it take into account all possible situations?

**Comment by serialseb** [comment] 2021-12-24 11:47
Your commit certainly looks simpler, but tracking usage just on one method calling that `ApplyLowStockActivityAsync` leads me to the following method and its usages:
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/212039/147349416-89d53e46-08ad-4d34-af65-da9b57affe33.png">

My understanding of it is, should the `_catalogSettings.PublishBackProductWhenCancellingOrders;` property be set to true, it would apply to *increasing* the stock on, just eye balling here, deleting and cancelling order.

I dont really know wnough about the other services here to understand the cyclomatic complexity of that method, so i tried to stay true to it's original intent. -1 if you move to order, +1 if you cancel or delete the order, and the other ones im not entirely sure of.

So i tried to say in my code the following: "If you're under the minimum stock, take whatever action is associated with that product when you reach that point". I only use unpublish so i tried to do the disabling of buttons in the way that looked intended. If you pass the code that checks for too little stock, then when that `_catalogSettings.PublishBackProductWhenCancellingOrders` setting is on,  publish it back.

I have no idea if it's the right logic for all scenarios, I'm not well versed enough in nopcommerce and especially its controllers. I am however seeing, as I believe you are too, that the current logic is absolutely broken, and I can't imagine how no one would've noticed, which makes me question how this code ever got this way.

It seems to me the refactoring in this commit changed the logic: https://github.com/nopSolutions/nopCommerce/commit/5e796b2ee88cc175abe700b6e5883c82f56910e8

I dont think the logic is the same at all, as it checked previously if you were decreasing, and then checking minimums before unpublishing. SHould you be increasing and the setting was set, then it would republish or reenable the buttons.

**Comment by skoshelev** [comment] 2021-12-24 13:17
hi, @serialseb. Thanks for the help. The behavior was really broken by the https://github.com/nopSolutions/nopCommerce/commit/5e796b2ee88cc175abe700b6e5883c82f56910e8 commit, everything worked fine before it, at least in the part that worked. Now it looks like the corrected logic should work without problems. I will close this ticket.

Closed #6040

**Closed by skoshelev** 2021-12-24 13:17 UTC
Labels: bug

**Comment by serialseb** [comment] 2021-12-24 13:24
It all comes down to semantics, i chose to be explicit on two branches with using `true` and `false` so no boolean logic was involved to understand what was going on, but I do believe your commit fixes the same problem in the same way, so I'm happy with it too.

Any chance it could be back ported on the 4.40-bug-fixes branch so i could rebase and remove my changes? I believe it's isolated enough to allow for that? Otherwise i'll cherry-pick it on my fork, i base most of my custom work on top of that branch (till the next release that is)

Thanks for looking into this @skoshelev and spending the time to reopen and fix the issue, it's very much appreciated and makes my life, and i'm sure many others, much easier.

Merry Christmas depending on your timezone!

**Comment by skoshelev** [comment] 2021-12-24 13:40
Thank you @serialseb for the congratulations and you, too, on the holiday. I pushed the changes to the 4.40-bug-fixes branch as well.
