### ISSUE TITLE
There is already an object named 'tmp_guestsToDelete' in the database.

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#6354] opened 2022-09-16 12:32 UTC
nopCommerce version: 4.50.3

Steps to reproduce the problem: 
1) I installed a fresh version of 4.50.3 on my localhost
2) It keeps just saying There is already an object named 'tmp_guestsToDelete' in the database.

Not sure how to fix:

`Log level
Error
Short message
The "Delete guests" scheduled task failed with the "One or more errors occurred. (There is already an object named 'tmp_guestsToDelete' in the database.)" error (Task type: "Nop.Services.Customers.DeleteGuestsTask, Nop.Services". Store name: "Your store name". Task run address: "http://localhost:65283/scheduletask/runtask").
Full message
System.AggregateException: One or more errors occurred. (There is already an object named 'tmp_guestsToDelete' in the database.)
---> Microsoft.Data.SqlClient.SqlException (0x80131904): There is already an object named 'tmp_guestsToDelete' in the database.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean isAsync, Int32 timeout, Boolean asyncWrite)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass31_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.CreateTable`1.Query(IDataContext dataContext, String tableName, String serverName, String databaseName, String schemaName, String statementHeader, String statementFooter, DefaultNullable defaultNullable, TableOptions tableOptions)
   at LinqToDB.TempTable`1..ctor(IDataContext db, IQueryable`1 items, String tableName, String databaseName, String schemaName, Action`1 action, String serverName, TableOptions tableOptions)
   at Nop.Data.TempSqlDataStorage`1..ctor(String storageName, IQueryable`1 query, IDataContext dataConnection) in C:\Users\dootc\source\repos\CigarsUntold\nopCommerce_4.50.3_Source\src\Libraries\Nop.Data\TempSqlDataStorage.cs:line 16
   at Nop.Data.DataProviders.BaseDataProvider.CreateTempDataStorageAsync[TItem](String storeKey, IQueryable`1 query) in C:\Users\dootc\source\repos\CigarsUntold\nopCommerce_4.50.3_Source\src\Libraries\Nop.Data\DataProviders\BaseDataProvider.cs:line 178
   at Nop.Services.Customers.CustomerService.DeleteGuestCustomersAsync(Nullable`1 createdFromUtc, Nullable`1 createdToUtc, Boolean onlyWithoutShoppingCart) in C:\Users\dootc\source\repos\CigarsUntold\nopCommerce_4.50.3_Source\src\Libraries\Nop.Services\Customers\CustomerService.cs:line 756
   at Nop.Services.Customers.DeleteGuestsTask.ExecuteAsync() in C:\Users\dootc\source\repos\CigarsUntold\nopCommerce_4.50.3_Source\src\Libraries\Nop.Services\Customers\DeleteGuestsTask.cs:line 41
ClientConnectionId:3c38d5a3-b289-4e66-b52c-c1c4261c8e42
Error Number:2714,State:6,Class:16
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Nop.Services.ScheduleTasks.ScheduleTaskRunner.ExecuteTask(ScheduleTask scheduleTask) in C:\Users\dootc\source\repos\CigarsUntold\nopCommerce_4.50.3_Source\src\Libraries\Nop.Services\ScheduleTasks\ScheduleTaskRunner.cs:line 79
   at Nop.Services.ScheduleTasks.ScheduleTaskRunner.<>c__DisplayClass8_0.<ExecuteAsync>b__0() in C:\Users\dootc\source\repos\CigarsUntold\nopCommerce_4.50.3_Source\src\Libraries\Nop.Services\ScheduleTasks\ScheduleTaskRunner.cs:line 146
   at Nop.Core.Caching.MemoryCacheManager.PerformActionWithLock(String key, TimeSpan expirationTime, Action action) in C:\Users\dootc\source\repos\CigarsUntold\nopCommerce_4.50.3_Source\src\Libraries\Nop.Core\Caching\MemoryCacheManager.cs:line 214
   at Nop.Services.ScheduleTasks.ScheduleTaskRunner.ExecuteAsync(ScheduleTask scheduleTask, Boolean forceRun, Boolean throwException, Boolean ensureRunOncePerPeriod) in C:\Users\dootc\source\repos\CigarsUntold\nopCommerce_4.50.3_Source\src\Libraries\Nop.Services\ScheduleTasks\ScheduleTaskRunner.cs:line 146
IP address
127.0.0.1
Customer
Page URL
http://localhost:65283/scheduletask/runtask
Referrer URL
Created on
9/16/2022 8:18:58 AM`

<img width="220" alt="image" src="https://user-images.githubusercontent.com/20989983/190639361-77dd8179-73a2-4fe8-b33d-accd4728a8ab.png">

**Comment by RomanovM** [comment] 2022-09-16 13:22
Duplicate of #5625

**Closed** 2022-09-16 13:22 UTC
