### ISSUE TITLE
CheckoutAttribute table is not created during installation process

### ISSUE THREAD

**Issue by karelkrivanek** [nopSolutions/nopCommerce#3321] opened 2018-09-21 18:46 UTC
nopCommerce version: 4.10

Steps to reproduce the problem: 

1. download and install nopCommerce with sample data (also works with clean DB)
2. add product to card - let's say a book
3. JS error appears
`Failed to add the product. Please refresh the page and try one more time.`
4. No other page in public store can be opened because of
`System.InvalidOperationException: Cannot create a DbSet for 'CheckoutAttribute' because this type is not included in the model for the context.
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in C:\MojeProjekty\nopCommerce_4.10_Source\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 83
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)`

This is probably duplicate of #3213 and #3201, would a DB backup (attached) help in replicating? I tried to build it from source, download no source and no source self contained versions, my dev machine and server but every time I get the same result
[wsaspokus.zip](https://github.com/nopSolutions/nopCommerce/files/2406586/wsaspokus.zip)

**Comment by RomanovM** [comment] 2018-09-24 06:59
It works correctly on our demo site, and it also works on my local machine (including the case with a new db).
[Here ](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Data/Mapping/Orders/CheckoutAttributeMap.cs)you can see the mapping class for the checkout attribute, so this type will be included in the model for the context.

**Comment by karelkrivanek** [comment] 2018-09-24 08:55
That's great that it works on your machine, but doesn't it strike as you as odd that 3 different users created this issue? I admit, that 3 isn't that much, but still

**Comment by RomanVdV** [comment] 2018-09-28 07:57
Same problem to me today.

**Comment by RomanVdV** [comment] 2018-09-29 22:50
> It works correctly on our demo site, and it also works on my local machine (including the case with a new db).
> [Here ](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Data/Mapping/Orders/CheckoutAttributeMap.cs)you can see the mapping class for the checkout attribute, so this type will be included in the model for the context.

Problem is in EntityFrameworkCorre, it depends on language settings and sorting, I tryed it. More info here [Entity type name is culture-sensitive](https://github.com/aspnet/EntityFrameworkCore/issues/12617). I am new to nopcommerce, but I think, that you can done quick fix, before bug will be fixed in EFC.

**Comment by zwierzyna-prosystem** [comment] 2018-10-04 09:17
I think CheckoutAttribute table si created correctly, but I found, that if you put 
`System.Threading.Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("en-US")` before ` TaskManager.Instance.Initialize()` at line 66 in class `ServiceCollectionExtensions` and function `ConfigureApplicationServices,` website seems to start working.

**Comment by zwierzyna-prosystem** [comment] 2018-12-04 12:46
Today i tried to migrate whole NopCommerce project to .Net Core 2.2 preview 3, installed last Microsoft.EntityFrameworkCore.SqlServer 2.2.0 NuGet and it looks like, that problems disappeared ...

**Comment by kocmour** [comment] 2019-03-13 21:59
After some investigation...
You can reproduce this problem by set the different culture then "en-Us" for working environment . Simply set different culture in CultureMiddleware class in SetWorkingCulture method (I use cs-CZ). 
Once you go to "Administration" culture is via CultureMiddleware hardcoded to "en-US" by. CommonHelper.SetTelerikCulture() some "hack due to telerik" and this seems to be "in some cases and I don´t know how to determine them" problem when getting Table from Datacontext. Seems like model for table are culture sensitive..?

**Comment by skoshelev** [comment] 2019-05-15 11:21
Can't reproduce on 4.20. Closed #3321

**Closed by skoshelev** 2019-05-15 11:21 UTC
Labels: discussion / investigation
