### ISSUE TITLE
Clear Cache With Distributed Cache

### ISSUE THREAD

**Issue by streamzyuk** [nopSolutions/nopCommerce#5593] opened 2021-04-07 00:23 UTC
nopCommerce version: 4.40.2

Steps to reproduce the problem:
Run Multiple Instance.
Login to Admin Area.
Select Clear Cache.
Check Redis Keys.
Only the key that are set by the instance are cleared.

Distributed cache manager holds a list of keys which are set by the instance running. It uses this list to clear the cache keys from redis. But when reading it does not check the keys  list. So understand that this list is used only for clearing the keys.

It may add the keys to the list when TryGetItemAsync returns true but this will not solve the problem since still only a portion of the keys will be stored.

Is there any purpose for it.

I expect clear cache to clear all keys in redis server or cluster.

There is no meaning of clearing the keys set by instance. Since it may not even set anything if the instance is created at later stage. Other instances may already created the cache keys.

**Comment by streamzyuk** [comment] 2021-04-07 01:48
This looks like causing other problems.
Changing settings from the admin area. Since the cache keys are not on the instance, settingsService.ClearCache does not clear anything at all.

**Comment by streamzyuk** [comment] 2021-04-07 13:44
public async Task ClearAsync()
        {
            //we can't use _perRequestCache.Clear(),
            //because HttpContext stores some server data that we should not delete
            var appSettings = Singleton<AppSettings>.Instance;
            var distributedCacheConfig = appSettings.DistributedCacheConfig;
            foreach (var redisKey in _keys)
                _perRequestCache.Remove(redisKey);

            /*
            using var _ = await _locker.LockAsync();

            foreach (var key in _keys) 
                await _distributedCache.RemoveAsync(key);
            */
            try
            {
                var connectionMultiplexer = ConnectionMultiplexer.Connect(distributedCacheConfig.ConnectionString + ",allowAdmin=true");
                var endpoints = connectionMultiplexer.GetEndPoints(false);
                foreach (var endpoint in endpoints)
                {
                    var server = connectionMultiplexer.GetServer(endpoint);

                    if (!server.IsSlave)
                    {
                        var keys = server.Keys(0,"Nop.*");
                        foreach(var key in keys)
                        {
                            await _distributedCache.RemoveAsync(key);
                        }
                       
                       // await server.FlushAllDatabasesAsync();
                    }
                }
                await connectionMultiplexer.CloseAsync(true);
            }
            catch (Exception e) {
                Console.WriteLine(e);
            }
            _keys.Clear();
        }
This is what I have tried. It works but it takes time. For 500 keys in a 6 node standard cluster it takes 458 ms. Basically 1 key deletion = 1 ms.
I tried flushdb. Its faster but with the side effect of deleting the SessionState  Keys which is not acceptable.
RemoveByPrefix method  may be changed to use the approach above for which have relatively less keys to delete.

But this should be fixed since the current code does not work with keys stored by instances.

**Comment by skoshelev** [comment] 2021-04-27 08:13
Unfortunately, we had to add our own list of keys to the DistributedCacheManager to compensate for the lack of methods of the IDistributedCache base interface. But unfortunately, the problem of completely clearing the distributed cache has not been solved yet, we are waiting for the implementation of [this ticket](https://github.com/dotnet/runtime/issues/44512) and the connection with it of smaller tasks

**Comment by streamzyuk** [comment] 2021-05-23 23:06
Yes I understand that. But the problem is Key List is Per instance which does not solve (actually create a real sync  problem with multi instance setup) key management problem in a multi instance setup.

**Comment by purplepiranha** [comment] 2021-08-24 12:49
I think this may be what's causing my problem too. If I edit any plugin settings they get saved to the database, but not updated in the cache, even after using the 'Clear Cache' button.

**Comment by sinaislam** [comment] 2021-11-23 05:09
> ClearAsync

Does this method solve your problem to remove cache for the Radis?

**Comment by purplepiranha** [comment] 2021-11-24 10:53
> > ClearAsync
> 
> Does this method solve your problem to remove cache for the Radis?

No.

I think there are 2 methods causing a problem here within `DistributedCacheManager`:
`ClearAsync()` - which should clear the entire cache but doesn't
`RemoveByPrefixAsync(string prefix, params object[] prefixParameters)` - which is called by `ISettingService.ClearCacheAsync()` when configuring a plugin. This can't be working because when a plugin's settings are saved and you return to the settings page it has the old values although a check in the database shows that they have changed.

It's also likely that `RemoveAsync(CacheKey cacheKey, params object[] cacheKeyParameters)` will have the same issue but I haven't looked into that yet.

**Comment by antoniodlp** [comment] 2021-12-09 00:20
What if we store the keys in a a cache entry? Then they would be distributed to all servers. 
Can someone tell me what the issue would be with that?

**Comment by sinaislam** [comment] 2021-12-09 05:11
> What if we store the keys in a cache entry? Then they would be distributed to all servers. Can someone tell me what the issue would be with that?

First of all, I do not test it myself. But if the below comment is true then it is a severe problem for auto-scaling.

"Yes, I understand that. But the problem is Key List is Per instance which does not solve (actually create a real sync problem with multi-instance setup) key management problem in a multi-instance setup."

If your fixing can resolve this issue then it would be good.

**Comment by szilardd** [comment] 2022-07-27 05:00
If you are using SQL Server as the data store, this might be a workaround until a better solution is available, by overriding the `DistributedCacheManager` in a plugin.

```cs
using System.Threading.Tasks;
using LinqToDB.Data;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Caching.Distributed;
using Nop.Core.Caching;
using Nop.Core.Configuration;
using Nop.Data;

namespace Plugin.Misc.MyPlugin.Services
{
    /// <summary>
    /// Overrides base cache manager and enables deleting all keys from database, 
    /// not just the ones that are currently in use. Related github issue:
    /// https://github.com/nopSolutions/nopCommerce/issues/5593
    /// </summary>
    public class MyPluginSqlServerDistributedCacheManager : DistributedCacheManager
    {
        private readonly INopDataProvider _dataProvider;
        private readonly string _tableName;

        public MyPluginSqlServerDistributedCacheManager 
        (
            AppSettings appSettings, 
            IDistributedCache distributedCache, 
            IHttpContextAccessor httpContextAccessor,
            INopDataProvider dataProvider
        ) : base(appSettings, distributedCache, httpContextAccessor)
        {
            _dataProvider = dataProvider;
            _tableName = appSettings.Get<DistributedCacheConfig>().TableName;
        }

        public override async Task ClearAsync()
        {
            // base delete
            await base.ClearAsync();

            // delete from database
            await _dataProvider.ExecuteNonQueryAsync($"TRUNCATE TABLE {_tableName}");
        }

        public override async Task RemoveByPrefixAsync(string prefix, params object[] prefixParameters)
        {
            // base delete
            await base.RemoveByPrefixAsync(prefix, prefixParameters);

            // delete from database
            prefix = PrepareKeyPrefix(prefix, prefixParameters);
            await _dataProvider.ExecuteNonQueryAsync
            (
                $"DELETE FROM {_tableName} WHERE Id LIKE @Prefix + '%'",
                new DataParameter[] { new DataParameter("Prefix", prefix) }
            );
        }
    }
}
```

And it needs to be registered in `INopStartup`

```cs
public class NopStartup : INopStartup
{
    public void ConfigureServices(IServiceCollection services, IConfiguration configuration)
    { 
        var appSettings = Singleton<AppSettings>.Instance;
        var distributedCacheConfig = appSettings.Get<DistributedCacheConfig>();
        if (distributedCacheConfig.Enabled && distributedCacheConfig.DistributedCacheType == DistributedCacheType.SqlServer)
        {
          services.AddScoped<IStaticCacheManager, MyPluginSqlServerDistributedCacheManager>();
        }
    }
}
```

`DistributedCacheManager.ClearAsync` and `DistributedCacheManager.RemoveByPrefixAsync` have to be marked as `virtual` in nop.

**Comment by sinanopcommerce** [comment] 2022-08-10 09:15
> If you are using SQL Server as the data store, this might be a workaround until a better solution is available, by overriding the `DistributedCacheManager` in a plugin.
> 
> ```cs
> using System.Threading.Tasks;
> using LinqToDB.Data;
> using Microsoft.AspNetCore.Http;
> using Microsoft.Extensions.Caching.Distributed;
> using Nop.Core.Caching;
> using Nop.Core.Configuration;
> using Nop.Data;
> 
> namespace Plugin.Misc.MyPlugin.Services
> {
>     /// <summary>
>     /// Overrides base cache manager and enables deleting all keys from database, 
>     /// not just the ones that are currently in use. Related github issue:
>     /// https://github.com/nopSolutions/nopCommerce/issues/5593
>     /// </summary>
>     public class MyPluginSqlServerDistributedCacheManager : DistributedCacheManager
>     {
>         private readonly INopDataProvider _dataProvider;
>         private readonly string _tableName;
> 
>         public MyPluginSqlServerDistributedCacheManager 
>         (
>             AppSettings appSettings, 
>             IDistributedCache distributedCache, 
>             IHttpContextAccessor httpContextAccessor,
>             INopDataProvider dataProvider
>         ) : base(appSettings, distributedCache, httpContextAccessor)
>         {
>             _dataProvider = dataProvider;
>             _tableName = appSettings.Get<DistributedCacheConfig>().TableName;
>         }
> 
>         public override async Task ClearAsync()
>         {
>             // base delete
>             await base.ClearAsync();
> 
>             // delete from database
>             await _dataProvider.ExecuteNonQueryAsync($"TRUNCATE TABLE {_tableName}");
>         }
> 
>         public override async Task RemoveByPrefixAsync(string prefix, params object[] prefixParameters)
>         {
>             // base delete
>             await base.RemoveByPrefixAsync(prefix, prefixParameters);
> 
>             // delete from database
>             prefix = PrepareKeyPrefix(prefix, prefixParameters);
>             await _dataProvider.ExecuteNonQueryAsync
>             (
>                 $"DELETE FROM {_tableName} WHERE Id LIKE @Prefix + '%'",
>                 new DataParameter[] { new DataParameter("Prefix", prefix) }
>             );
>         }
>     }
> }
> ```
> 
> And it needs to be registered in `INopStartup` of the plugin
> 
> ```cs
> public class NopStartup : INopStartup
> {
>     public void ConfigureServices(IServiceCollection services, IConfiguration configuration)
>     { 
>         var appSettings = Singleton<AppSettings>.Instance;
>         var distributedCacheConfig = appSettings.Get<DistributedCacheConfig>();
>         if (distributedCacheConfig.Enabled && distributedCacheConfig.DistributedCacheType == DistributedCacheType.SqlServer)
>         {
>           services.AddScoped<IStaticCacheManager, MyPluginSqlServerDistributedCacheManager>();
>         }
>     }
> }
> ```
> 
> `DistributedCacheManager.ClearAsync` and `DistributedCacheManager.RemoveByPrefixAsync` have to be marked as `virtual` in nop.

True. But actual issue is the cache is per instance when use the distributed cache.

**Closed** 2022-09-26 14:15 UTC
Labels: refactoring / source code

**Comment by AdiIndoSwiss** [comment] 2023-03-02 14:02
I tried this solution still the cache doesn't load properly in 4.5.01. any suggestions need quickly a working solution. I tried overwriting the distributedcache one but no luck.
