### ISSUE TITLE
Size of Repo and possible option to purge old DLL's. Consider pruning

### ISSUE THREAD

**Issue by jafin** [nopSolutions/nopCommerce#7004] opened 2024-01-14 02:27 UTC
## Steps to reproduce the problem: 

Checking out NopCommerce repo is approx `1.08gb`, as of 14/1/24 which is quite large.  This may also impact build times if the CI agent has to pull the repo down.

Scanning the repository for large files, shows that history where various dll's were committed. (And possibly shouldn't be?)

Using https://rtyley.github.io/bfg-repo-cleaner/

Delete the files
```shell
java -jar bfg.jar --delete-files Nop.Services.dll
java -jar bfg.jar --delete-files Nop.Web.dll
java -jar bfg.jar --delete-folders bin
java -jar bfg.jar --delete-folders packages
```

Purge from repo
```shell
git reflog expire --expire=now --all && git gc --prune=now --aggressive
```

Push changes
```shell
git push origin --force --all
```

This should remove files that in principal can all be rebuilt from source, and nuget restored from web. So should not impact someone building an earlier release.

After running the above, repo size was, `559M` , so a saving of over `500M`

I can't submit this as a PR as it is rewriting history across branches, so raising as an issue for consideration.

Command to show all the large files

```sh
git rev-list --objects --all |   git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |   sed -n 's/^blob //p' |   sort --numeric-sort --key=2 |   cut -c 1-12,41- |   $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest
```

**Comment by RomanovM** [comment] 2024-01-15 04:51
Duplicate of #5762

**Closed** 2024-01-15 04:51 UTC

**Comment by jafin** [comment] 2024-01-15 10:22
Sorry I didn't see the duplicate.
