### ISSUE TITLE
The Value "" is invalid on Tax categories page 

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#4563] opened 2020-04-13 18:15 UTC
nopCommerce version: 4.30

Steps to reproduce the problem: 
Go to Tax categories page
Add category without add display order
![11](https://user-images.githubusercontent.com/13154058/79146677-5e82d400-7de0-11ea-8a6f-581dd68b762a.png)

Note: Using latest source code, you can see in video.

See this video - https://www.loom.com/share/ed244c6df3874847b72589ab5487cfd5

**Comment by skoshelev** [comment] 2020-04-13 19:07
Duplicate of #4522

**Closed by skoshelev** 2020-04-13 19:07 UTC

**Comment by rajupaladiya** [comment] 2020-04-13 19:11
@skoshelev - I agree it duplicate of #4522, but the issue is still there even #4522 is fixed and close.
I clearly mentioned that using the latest source code and also show that in video.

Have you checked this or direct closed?

**Comment by skoshelev** [comment] 2020-04-13 19:14
Hi @rajupaladiya. I apologize, I watched the video after I marked the question as a duplicate. The essence of the main problem was not to try to save the empty value, but that after saving the value was not cleared correctly. And if you simply delete the correct value with your hands, I don’t see a problem in this.

**Comment by rajupaladiya** [comment] 2020-04-13 19:17
Here I'm talking about the validation message which not appropriate.

**Comment by skoshelev** [comment] 2020-04-13 19:28
Ok, @rajupaladiya. I'm sorry, from your description or the name of the ticket, I could not figure out what exactly you want to say. Please create a new task with a proposal to change the verification message

**Comment by rajupaladiya** [comment] 2020-04-13 19:30
Okay, I'll do. Thanks @skoshelev.

**Comment by rajupaladiya** [comment] 2020-04-13 19:34
@skoshelev Here is new task - #4564
