### ISSUE TITLE
Google Authenticator. Allow a store owner to configure customer roles that will be used in the plugin (restrict by role)

### ISSUE THREAD

**Issue by shoecake** [nopSolutions/nopCommerce#6292] opened 2022-06-24 11:10 UTC
Feature request: Extend the Google Authenticator plugin so only users in specific roles can use it.
 
I would like to use Google Authenticator, but only for the site administrators. I think for my customers it is not needed and could cause a number of support issues or even lost sales if the customer cannot log in. 

Also, if the customer is not in the right role, then they would not see the option to set it up in their account.

**Comment by RomanovM** [comment] 2022-06-24 11:40
Duplicate of #5607

**Closed** 2022-06-24 11:40 UTC
Labels: functionality / feature
