### ISSUE TITLE
Bestsellers report invalid item count

### ISSUE THREAD

**Issue by RomanovM** [nopSolutions/nopCommerce#3498] opened 2019-01-14 08:48 UTC
Source: https://www.nopcommerce.com/boards/t/57688/bestsellers-report-invalid-item-count.aspx

**Comment by MaxMommersteeg** [comment] 2019-01-14 21:56
Strangely enough I could not reproduce this issue locally, but do see described behavior at the admin demo website.

**Comment by RuS984** [comment] 2019-01-18 12:05
This issue is fixed in version 4.20
Closed #3498

**Closed by RuS984** 2019-01-18 12:05 UTC
Labels: bug
