### ISSUE TITLE
Filtering products by stores in the admin doesn't work

### ISSUE THREAD

**Issue by untiedshoes** [nopSolutions/nopCommerce#6747] opened 2023-06-28 17:12 UTC
nopCommerce version: 4.60.3

Steps to reproduce the problem: Filtering products by stores in the admin doesn't work, shows all products, no matter which store is selected.

![Screen Shot 2023-06-28 at 18 12 05](https://github.com/nopSolutions/nopCommerce/assets/12123259/eb6b9447-220f-4c2e-b60e-8999d7acaf84)

**Comment by RomanovM** [comment] 2023-06-29 10:47
Duplicate of #6615

**Closed** 2023-06-29 10:47 UTC
