### ISSUE TITLE
Simple product always out of stock

### ISSUE THREAD

**Issue by DamienLaw** [nopSolutions/nopCommerce#6070] opened 2022-01-10 08:13 UTC
On the product page, on first load, the availability is always **Out of stock** although this product has stock for all product attributes.
![image](https://user-images.githubusercontent.com/14930009/148731523-191f830e-69fc-4035-87f0-90c3db731daf.png)

However, upon selecting any of the product attributes, the availability is updated correctly.
![image](https://user-images.githubusercontent.com/14930009/148731789-9265ba8e-b81d-48a2-898c-6973c9f285fc.png)

nopCommerce version: 4.40.4

Steps to reproduce the problem: 

1. Create a Simple product.
2. Configure the Inventory as follows
![image](https://user-images.githubusercontent.com/14930009/148732152-9b742902-f7be-4e0f-a83c-53f1c811a6fa.png)
3. Set Product Attributes
![image](https://user-images.githubusercontent.com/14930009/148732349-d0f90269-5850-47b7-bdac-67cc4affce24.png)
4. Generate Attribute Combinations, make sure all of them has stocks.
![image](https://user-images.githubusercontent.com/14930009/148732459-e9795ff6-4a1d-401f-8f8f-b6571d5747cc.png)
5. Save and view the product in public store front.

This could be due to `string.Empty` being passed in as `attributesXml`.
https://github.com/nopSolutions/nopCommerce/blob/42b3ae8a15f117d54c84a8a2610b86f936a15fd2/src/Presentation/Nop.Web/Factories/ProductModelFactory.cs#L1381

Which will always display **Out of stock**.
https://github.com/nopSolutions/nopCommerce/blob/5600a791804ae0dbdcc397ed717333382317e340/src/Libraries/Nop.Services/Catalog/ProductService.cs#L288

**Comment by skoshelev** [comment] 2022-01-10 13:28
Duplicate of #5510

**Closed by skoshelev** 2022-01-10 13:28 UTC
Labels: discussion / investigation
