### ISSUE TITLE
Proper Invoice system

### ISSUE THREAD

**Issue by AxelAndersen** [nopSolutions/nopCommerce#6646] opened 2023-03-11 08:48 UTC
### Issues with current invoicing

1. In NopCommerce today an Invoice is the same as an order.
    The invoice number will be the order number.
    This is not correct in regards to EU legislation where a list of invoices must be in an unbroken sequence.
    So if just one order is not paid, or cancelled, we have a broken list of invoice numbers.

2. It is also a problem that we cannot split an order into multiple invoices.
   Consider an order for 5 items, and the 3 of them are in stock, the rest are not.
   The customer would like the 3 now, and the rest when it is back in stock. 
   We need to ship the 3, and send the customer an invoice for those 3 items. 

3. Another problem is how to create a credit note when an item is returned.
   The credit note may not be for the full order amount but only 1 item for the order.
   This should be reflected in the credit note. 
   By law it is also important that a credit note is part of the same unbroken sequence of invoice numbers.

### Suggestion:

New database table containing only invoices and credit notes.
When shipping items, an invoice is created for those items in shipping list.
A new message template for invoice is created, and used to sent to the customer.

If an item is returned to the shop:
The money will be refunded for that item.
A credit note created for that item and sent to the customer.

A list of invoices can be seen by an admin in NopCommerce

**Comment by RomanovM** [comment] 2023-03-12 07:19
@AxelAndersen Thanks for your suggestions and reasoning. We'll consider this in #5.

**Comment by RomanovM** [comment] 2023-03-12 07:19
Duplicate of #5

**Closed** 2023-03-12 07:19 UTC
