### ISSUE TITLE
Use referrer url to find the correct breadcrumb instead of the first productcategory foun

### ISSUE THREAD

**Issue by lintho** [nopSolutions/nopCommerce#7141] opened 2024-04-17 08:19 UTC
nopCommerce version: 4.6

Steps to reproduce the problem: 
navigate to a product with several product categories
first productcategory added on the product is whats being used to generate breadcrumb
the breadcrumb should instead be generated by the previous path the user was on (the category)

**Comment by RomanovM** [comment] 2024-04-17 08:29
Duplicate of #5776

**Closed** 2024-04-17 08:30 UTC
