### ISSUE TITLE
Async methods (performance)

### ISSUE THREAD

**Issue by DarthSonic** [nopSolutions/nopCommerce#2287] opened 2017-04-03 07:55 UTC
Based on discussion http://www.nopcommerce.com/boards/t/41947/performance-testing-nopcommerce-370-on-azure-using-redis-blob-azure-sql.aspx here  are some suggestions for better performance in Azure enviroment (and even outside Azure)

also see  http://www.nopcommerce.com/boards/t/46712/nopcommerce-400-roadmap-and-estimated-release-date-lets-discuss.aspx?p=2#185433

We have to introduce more async methods (actually covering all request) - controllers, services, database calls, etc

**Comment by lintho** [comment] 2017-04-03 10:22
Good work. I hope the team will take this seriously!

**Comment by chadwixk** [comment] 2017-04-03 17:05
There's no way to Vote up in Git...but using a comment as such. Hope the Nop Team evaluates this seriously ...and soon!

**Comment by almarax** [comment] 2017-04-04 13:32
I'd be more specific in p.4 - do not query DB multiple times when you can easily use your own optimization improvement: 
QueryableExtensions.IncludeProperties<T>() 
to preload all related data in the first query, This will significantly lower used DTUs in Azure and make pages much more responsible, especially considering latency of every query on lower Azure plans.

**Comment by martingust** [comment] 2017-04-05 16:25
Great, I think this is a deal breaker for a lot of people.

**Comment by pdunleavy** [comment] 2017-04-18 10:47
Please can we add async calls to blob storage (AzurePictureService) this looks to be using a static reference which is torn down on every request, not sure of the internals of the storage api but getpicturethumb gets a lot of hammering and this could cause a scalability bottleneck if requests are being queued synchronously to access the container.

**Comment by pdunleavy** [comment] 2017-04-27 12:34
The category listing page uses a stored procedure to retrieve the paged list of products, I need more than QueryableExtensions.IncludeProperties() to include product picture records almarax. This would need refactoring to be multi result set...  http://stackoverflow.com/questions/10314032/entity-framework-5-stored-procedure-with-multiple-result-sets

**Comment by pdunleavy** [comment] 2017-04-28 08:37
Just want to say, we have now moved our site to a single Azure VM with the same specification. All pages now load 1 second faster than web app with sql azure. If this work item can be done we can consider moving back.

**Comment by lintho** [comment] 2017-09-14 13:07
Is there any updates on this? We host in azure, and we need better performance.

**Comment by AndreiMaz** [comment] 2017-10-06 10:01
Please sorry and ignore that it's in Russian (only for internal use)

Optimization. предлагаю обсудить, что мы можем сделать для версии 4.0
1. предлагаю вернуться к задаче - Use async controller when requesting third-party services. использовать асинхронные методы в наших сервисах, которые взаимодействуют со сторонними сервисами. читай все, что связаны с плагинами, с azure, с redis. а возможно и вообще все сервисы сделать асинхронными, поскольку все они так или иначе взаимодействуют друг с другом.
2. вытекает из предыдущего пункта - сделать все методы контроллеров асинхронными. поддержка этого со стороны mvc есть.
3. соответственно обновить наши плагины на использование async запросов к сторонним сервисам. там, где это невозможно, просто использовать крупномодульную асинхронность вида Task.Run(() => {}).
4. предлагаю реализовать также эту задачу Add async support for events. сделать вызовы и обработку событий асинхронными.
5. подумать об асинхронном выполнении schedule tasks.
6. мы добавили long-term кэширование language, currency, store - Performance. More presentation model caching. нужно подумать, какие еще сущности кэшировать таким же образом. может все?
7. подумать, в каких методах мы можем использовать TableNoTracking для сущностей - типа как здесь Performance. GetAllUrlRecordsCached method of UrlRecordService should use "TableNoTracking"
8. подумать об улучшении взаимодействия с бд, возможно дополнительные индексы или хранимые процедуры. еще какие-то идеи? мне особо нечего предложить.
9. еще у кого какие мысли?
10. сделать взаимодействие с бд асинхронным? вроде entity framework это поддерживает

**Comment by AndreiMaz** [comment] 2017-10-10 14:36
We have only tasks related to async left in this task. so I've just renamed it. For further chane I would suggest to create separate work items

**Comment by rreaddev** [comment] 2018-06-14 12:08
Please add more async method support to improve Redis caching scalability.

**Comment by fendric** [comment] 2018-06-14 14:55
I second this motion. Redis is unusable in its current state in NOP 4.0.

**Comment by kmaklakova** [comment] 2018-06-14 15:05
Confirming that Redis is not usable with NOP 4.

**Comment by yaronbsmtx** [comment] 2018-06-27 16:00
Same here, performance drops tens of percents when Redis is in use.
Any plans for 4.1?

**Comment by skoshelev** [comment] 2019-02-18 12:09
We shouldn't forget about #1275

**Comment by galvesribeiro** [comment] 2020-08-21 03:34
Hey folks!

We've evaluating use nopCommerce to a new project but while reading the code, I realised that all the calls to the database are blocking calls using the non-async methods. In particular the `INopDataProvider` and its friends...

Is there a plan to make them all async? ASP.Net core is completely non-blocking architecture and those calls are hurting a lot performance...

Thank you!

**Comment by galvesribeiro** [comment] 2020-08-24 22:02
Yeah that is exactly our usecase. We managed in a simulation to distribute it across hundreds of containers, but it wasting a lot of resources on the host machines not to mention the resources over Azure SQL itself... It would be really great to have they moved to async since the whole ASP.Net Core runtime is based on it and blocking their threds is something really bad. 

I would say that if you want to use those blocking calls, better stick with older versions of nopCommerce with .Net Framework and don't move to .Net Core until this get fixed.

**Comment by untiedshoes** [comment] 2020-08-29 11:33
We've done some load testing on our sites again, and thought I'd share the results.

Dev 4.30
25: [https://bit.ly/32Cxc6Y](url)
30: [https://bit.ly/31AqeA1](url)
40: [https://bit.ly/2EsuoS6](url)
1000 load: [https://bit.ly/2EIq9BD](url)
 
Base 4.00 - no products / categories etc
25: [https://bit.ly/2YHTPWJ](url)
30: [https://bit.ly/31zyMHp](url)
40: [https://bit.ly/32CrT7P](url)
1000 load: [https://bit.ly/2QtMgya](url)
 
Live 4.00
25: [https://bit.ly/34HXW8S](url)
30: [https://bit.ly/3lrCxa4](url)
40: [https://bit.ly/31yxeh1](url)

Dev 4.30 can handle more clicks per second. 40 was fine on dev 4.30 (probably take more). 40 failed on the live site pretty quickly.

Dev 4.30
40 load single page: [https://bit.ly/34Fw4lH](url)
40 load two page: [https://bit.ly/3lrLWyo](url)
 
50 slow: [https://bit.ly/2G0V1O9](url)
60 fail: [https://bit.ly/3gwEK04](url)
 
Looks like 40 is the limit.

Yesterday, on our live 4.00 site, we had a serious issue though, with Almost 1000 anonymous users and 200-250 current connections. Threads over a 1000! This basically killed the server, and we couldn’t restart the site! We had to very quickly implement some queue software to be able to restart the site and limit the connections.

We should have the 4.30 dev rolled over to live by the 7th, and have recently implemented a few 4.40 performances fixes such as [https://github.com/nopSolutions/nopCommerce/commit/eda728b37a9b92d8a7c2be4c08bf606e6b3b011e](url) and yesterday, 'IVersionLoader makes many DB requests on resolve #5004'.

Regards,
Craig

**Comment by untiedshoes** [comment] 2020-08-29 11:45
Quick question - will implementing #5000 break 4.30, and any plugins? If not, then I'll make these changes to our development of 4.30 straightaway.

**Comment by untiedshoes** [comment] 2020-08-31 11:13
More tests again today on our 4.30. We thought we'd warm up the site first prior to the main tests - warm-up, 0 - 200 clients over 10mins on one URL.

At 5 mins in, we start to get timeouts, and the response time, of course, goes through the roof.

![Screen Shot 2020-08-31 at 11 40 16](https://user-images.githubusercontent.com/12123259/91712003-d2026380-eb7e-11ea-8dac-bcb6288141ec.png)
![Screen Shot 2020-08-31 at 11 40 29](https://user-images.githubusercontent.com/12123259/91712009-d4fd5400-eb7e-11ea-88f5-776cdd26e5a7.png)

By the way, we've pushed #5004 to our 4.30.

We're also using Azure CDN for all static files, and of course, images. Not using Redis as we've always found it to reduce overall performance considerably.

30 clients on 1 url for 2 mins. Fine, with the following response times: Average: 2023ms, min/max: 620 / 4833ms.
40 clients on 1 url for 2 mins. Fine, with the following response times: Average: 2995ms, min/max: 765 / 6553ms.
0 - 1000 clients on 1 url for 2 mins. Fail.

![Screen Shot 2020-08-31 at 11 56 24](https://user-images.githubusercontent.com/12123259/91713117-0ecf5a00-eb81-11ea-9c66-897ae901bf70.png)
![Screen Shot 2020-08-31 at 11 56 09](https://user-images.githubusercontent.com/12123259/91713121-11ca4a80-eb81-11ea-84bc-7a09c87a1eb9.png)

We did 45 clients over 1 url for 2 mins, and although it passed, response times were slow: Average: 3065ms Min/Max: 660 / 7455ms.

**Comment by galvesribeiro** [comment] 2020-08-31 11:16
Damn man, that is freaking slow... :/

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lintho** [comment] 2020-08-31 11:25
We did a stresstest in azure and we experienced the same, but that was for 4.1. 200 clients stresstesting with azure tool crashed the site completely.  And 200 clients during a sale isnt much tbh. I dont know if the stress test in azure operates as a user does though.

**Comment by galvesribeiro** [comment] 2020-08-31 11:28
I will see what I can do when I have some time to convert to async and see what happens...

In meanwhile, it would be good that you guys share a generic benchmark code somewhere so we can use the same tests to measure it...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by untiedshoes** [comment] 2020-08-31 11:31
> I will see what I can do when I have some time to convert to async and see what happens ... In meanwhile, it would be good that you guys share a generic benchmark code somewhere so we can use the same tests to measure it. .. Get Outlook for iOS < https://aka.ms/o0ukef >
> [...](#)
> ________________________________ From: Sindre Markussen <notifications@github.com> Sent: Monday, August 31, 2020 8:25:42 AM To: nopSolutions/nopCommerce <nopCommerce@noreply.github.com> Cc: Gutemberg Ribeiro <gutemberg@outlook.com>; Comment <comment@noreply.github.com> Subject: Re: [nopSolutions/nopCommerce] Async methods (#2287) We did a stresstest in azure and we experienced the same, but that was for 4.1. 200 clients stresstesting with azure tool crashed the site completely. And 200 clients during a sale isnt much tbh. I dont know if the stress test in azure operates as a user does though. — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FnopSolutions%2FnopCommerce%2Fissues%2F2287%23issuecomment-683721035&data=02%7C01%7C%7Cfebed190719c4ffd5ec008d84da0990a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637344699433589891&sdata=ZiHI0CtKcarficE5pEYfpi49XKeez%2BNBdcHRy5mIfcA%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABD64OBARBOWWXNT2BZFFXDSDOCDNANCNFSM4DGEZPYA&data=02%7C01%7C%7Cfebed190719c4ffd5ec008d84da0990a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637344699433599882&sdata=6OlIyRQjHPjObobjX5Rtp1HmGLMXpjvC3x9D0pcdKpk%3D&reserved=0>.

If you check #4964, you'll see some base tests for 4.30.

**Comment by untiedshoes** [comment] 2020-08-31 11:41
> We did a stresstest in azure and we experienced the same, but that was for 4.1. 200 clients stresstesting with azure tool crashed the site completely. And 200 clients during a sale isnt much tbh. I dont know if the stress test in azure operates as a user does though.

The test basically simulates 200 clients per second, all clicking refresh. The max we've found is 50, but response times were not great. 60, failed!

50 clients per second, one url, 2 mins.
![Screen Shot 2020-08-31 at 12 39 22](https://user-images.githubusercontent.com/12123259/91716210-12fe7600-eb87-11ea-9089-b4418cf4424e.png)


On our current 4.00 multi-store, we've had over 600 users on the site at one time with next to zero impact on performance, with over 700 orders, and 700 new customer registration (genuine) in one day.

Our main issue is the initial load - i.e. say 50 to 100 clients on the site, then a large increase (e.g. when a mailshot goes out / social media announcement about a new kit release), and traffic increases significantly in a very short time.

It certainly looks like 4.30 can handle this better, but it isn't spectacular considering this is an issue that's been ongoing since 2017.

**Comment by untiedshoes** [comment] 2020-08-31 11:46
Personally, I'd like to see some load tests on a load-balanced server (azure, with auto-scaling), to see if this could help? At the moment, I'm not able too, but we have an extremely well specced dedicated server.

Dual E5-2620 v3 CPU’s
Dual 1TB SSD in raid 1
128GB ECC ram
Windows Server 2019 on SSD
IIS 10
MSSQL, with web licence, on the same server
Plesk
1Gb/s port
All files on an NVMe (No difference in performance between using the NVMe, and having files on SSD)

**Comment by untiedshoes** [comment] 2020-09-09 16:55
Following on from my previous comments, we've finally moved our 4.00 multi-store to 4.30.

The development version, albeit with only a single store, and fewer products/categories, can handle 25 clients per second, 30 & 40 being the max 'useable'. These tests are shown above.

We've done some testing this morning on the newly upgraded site - it can't even handle 25 clients a second, and falls flat on its face within 10 seconds!!

We've cleaned up the DB, reindexed, but still the same. All settings are the same across the live & dev sites.

What on earth is going on with nopCommerce?! I'll be honest, I think we're getting very close to finding another solution, and joining many others than have moved to a new eCommerce solution.

I'm sorry for the rant, but we are getting so much aggravation from the client over this.

**Comment by lintho** [comment] 2020-09-14 17:05
This isnt very good PR for nopcommerce as a solution, and i think it should be adressed\commented on by a nopcommerce employee.

**Comment by untiedshoes** [comment] 2020-10-02 11:03
> > Following on from my previous comments, we've finally moved our 4.00 multi-store to 4.30.
> > The development version, albeit with only a single store, and fewer products / categories, can handle 25 clients per second, 30 & 40 being the max 'useable'. These tests are shown above.
> > We've done some testing this morning on the newly upgraded site - it can't even handle 25 clients a second, and falls flat on its face within 10 seconds !!
> > We've cleaned up the DB, reindexed, but still the same. All settings are the same across the live & dev sites.
> > What on earth is going on with nopCommerce ?! I'll be honest, I think we're getting very close to finding another solution, and joining many others than have moved to a new eCommerce solution.
> > I'm sorry for the rant, but we are getting so much aggravation from the client over this.
> 
> @untiedshoes The problem with performance is related to the amount of queries running for each operation and a wrong use of caching. They claim the problem was EF Core but it sits in the way they have defined the db model and the way it is queried.
> It works fine if you have a bunch of categories but when your catalog grows NopCommerce simply cannot keep up.

Yep, there's certainly something serious going on! Our 'upgrade' for the client from 4.00, to 4.30 has massively reduced the number of connections the site can handle. Because this site is a multi-store, for football clubs, it puts our client in a very difficult position with their own clients.

Our 4.00 could handle 25 clients per second... just! Our current 4.30 fails on 25, and the maximum is 10. With Christmas coming up, this is now quite a serious issue.

The development 4.30 version, as mentioned above could do 40 clients per second (50, at a push), and is identical in every way, apart from the number of categories, customers etc,

25 clients per second:
![Screen Shot 2020-10-02 at 11 57 08](https://user-images.githubusercontent.com/12123259/94916357-72adb100-04a6-11eb-9ab0-8f27f1343f2f.png)

10 clients per second:
![Screen Shot 2020-10-02 at 11 57 45](https://user-images.githubusercontent.com/12123259/94916398-878a4480-04a6-11eb-836e-c2112a39e1e6.png)

Regards,
Craig

**Comment by tekguy** [comment] 2020-10-02 11:39
@untiedshoes are these performance tests located somewhere? I'd like to run against our configuration to see if we get similar results. Our 4.3 app is deployed in azure.

Thanks

**Comment by untiedshoes** [comment] 2020-10-02 11:47
> @untiedshoes are these performance tests located somewhere? I'd like to run against our configuration to see if we get similar results. Our 4.3 app is deployed in azure.
> 
> Thanks

Hi,

The vast majority of our tests are shown above, and also here #4964 

We're using loader.io by the way.

**Comment by joekrauss** [comment] 2020-10-02 12:09
I agree with the test results provided by @unitedshoes when it comes to the failure rate. Has anyone tested a generic net core site to see if the issue is with net core itself? What if this issue is a Microsoft problem and we are limiting our test parameters to only a NopCommerce site.

Thanks & Stay Safe!
Joseph Krauss

Sent from my iPhone

> On Oct 2, 2020, at 6:48 AM, untiedshoes <notifications@github.com> wrote:
> 
> ﻿
> @untiedshoes are these performance tests located somewhere? I'd like to run against our configuration to see if we get similar results. Our 4.3 app is deployed in azure.
> 
> Thanks
> 
> Hi,
> 
> The vast majority of our tests are shown above, and also here #4964
> 
> We're using loader.io by the way.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.



Defense Solution Group, Inc. / DSG Arms
Office: 817-806-9242
Fax: 817-615-8820
Email: 
6100 Conveyor Drive
Cleburne, TX 76031-0998
CAGE: 1L0J5
GSA: GS-07F-6007R 
https://dsgarms.com
https://www.dsgholsters.com
http://www.dsginc.com
The content of this email is confidential and intended for the recipient specified in the message only. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future.

**Comment by nirupamduet** [comment] 2020-10-03 04:01
Redis will not work.
But all you need to add more caching,
Reduce db call, split GenericAttribute table, stop checking image file
existence and some custom development.

You could use stackify to figure it out.

BTW, we have a store(4.0) with a lots of customization, it could hardly
serve 400+, after 2/3 months of optimization it can easily serve 2000+
(Google analytic).

We are using two c5.xlarge app instances and c5.2xlarge db instances.

**Comment by untiedshoes** [comment] 2020-11-30 18:39
We've managed to make some progress with our 4.30 site. We can now handle 80 clients a second - using various more aggressive caching, and multiple worker processes (between 4 & 6). Not exceptional, but certainly better than we were experiencing.

The downside to this is, of course, we now have instances of the scheduled tasks running more than once - order emails for instance.

I've tried using a mutex, but as Mutex in .net core 3.1 only accepts three arguments, I can't pass through MutexSecurity() - trying without, crashes the app pool.

Does anyone have a quick fix for this - scheduled tasks in a web garden?

4 x Worker Processes:
![4xworker](https://user-images.githubusercontent.com/12123259/100649912-0b439e80-333b-11eb-8a47-bc3df18eced5.png)

6 x worker processes
![6xworker](https://user-images.githubusercontent.com/12123259/100649938-14347000-333b-11eb-8457-289922a223f7.png)

Thanks,
Craig

p.s. I see progress is being made on the async methods :)

**Comment by tekguy** [comment] 2020-11-30 19:59
@untiedshoes  Very good progress!

Correct me if I am wrong when you say "worker" I am assuming you mean a node/instance in a web farm. In that case I don't see how mutex would help in this situation if the app is deployed to 4, 6 or X number of workers/nodes. A `mutex `will operate on a single app pool (IIS definition)

In our case I couldn't find a solution from NOP itself for preventing scheduled jobs from executing on multiple nodes. So we are planning to roll our own, which involves:

1. Randomly assigning a node in the web farm as the schedule task executioner. In our situation, we are running on Azure (app service). And resources are moved around in the cloud, so your app can be running on one server in azure today and possibly another tomorrow. So we are planning to constantly re-assign a valid task executioner (based on the machine name, https://docs.microsoft.com/en-us/dotnet/api/system.environment.machinename?view=net-5.0). We will this machine name and store it as a setting in the setting table, we will run this process as a background job, taking advantage of `IHostedService`, https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/hosted-services?view=aspnetcore-3.1&tabs=visual-studio

2. We are placing additional logic in the following area (where the task are executed): [Task class](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Tasks/Task.cs#L76)
Here we will check the computer name that is executed on matches what we have stored in the database.

We haven't done this work yet, but this was my initial idea. Obviously you don't have to create step 1 if you know the machine name of each node in your webfarm won't change to reduce the complexity. You can simple just store that machine name in appsettings.json.

Hope this helps!

As a side note, also looking forward to the async methods PR!

**Comment by untiedshoes** [comment] 2020-11-30 20:29
@tekguy 

Thanks for the reply 👍 

By worker processes, I mean app pool worker processes. Increasing from the standard 1, to 4/6. We’ve tried NUMA in the past, but had issue with it.

The issue of the scheduled task sending multiple emails when you increase worker processes has been around for a long time, and has never really been addressed.

The performance increase we’ve made is great, but we can’t really push it to the live site of the client / customers are going to get multiple emails for every order placed,

For instance, I put an order through earlier, and I received 2 store owner emails, and three customer emails.

Thanks,
Craig

**Comment by mattisax** [comment] 2020-12-01 00:48
@untiedshoes 

Curious about your load test. Are all the users making multiple requests to the same url for a minute, or does a user make a single request to the url and then they are done? Also, what type of environment are you testing against?

We recently (few weeks ago) went through some battles with Nop 4.3 performance but ended up making a few changes that gave us a big improvement. Sites performed great through Black Friday/Cyber Monday. Busiest of the sites averages around 3k request per minute during peak hours. That is requests actually hitting the web server. Cloudflare is being used too. These are all single instance sites. We are going to explore horizontal scaling in the near future. Here are the changes. The top two take minutes but gave us big bang for the buck.

1. Port this commit back to Nop 4.3, build, and redeploy the updated Nop.Data.dll: https://github.com/nopSolutions/nopCommerce/commit/56e4594e3419ff672dafe2d9b4f252842934188a
2. Change GC settings in Nop.Web.runtime.config. "System.GC.Concurrent", "System.GC.Server", and "System.GC.RetainVM" should all be set to true.
3. We were trying to override Nop's memory cache implementation since it seems to be clearing itself excessively, but ended up just creating our own cache with EasyCaching that is used by our own plugins.

Ken

**Comment by untiedshoes** [comment] 2020-12-01 07:19
> @untiedshoes
> 
> Curious about your load test. Are all the users making multiple requests to the same url for a minute, or does a user make a single request to the url and then they are done? Also, what type of environment are you testing against?
> 
> We recently (few weeks ago) went through some battles with Nop 4.3 performance but ended up making a few changes that gave us a big improvement. Sites performed great through Black Friday / Cyber ​​Monday. Busiest of the sites averages around 3k request per minute during peak hours. That is requests actually hitting the web server. Cloudflare is being used too. These are all single instance sites. We are going to explore horizontal scaling in the near future. Here are the changes. The top two take minutes but gave us big bang for the buck.
> 
> 1. Port this commit back to Nop 4.3, build, and redeploy the updated Nop.Data.dll: [56e4594](https://github.com/nopSolutions/nopCommerce/commit/56e4594e3419ff672dafe2d9b4f252842934188a)
> 2. Change GC settings in Nop.Web.runtime.config. "System.GC.Concurrent", "System.GC.Server", and "System.GC.RetainVM" should all be set to true.
> 3. We were trying to override Nop's memory cache implementation since it seems to be clearing itself excessively, but ended up just creating our own cache with EasyCaching that is used by our own plugins.
> 
> Ken

Hi Ken,

Load tests are done via loader.io - as far as I'm aware, the load (basically), simulates x amount of clients, hitting refresh every second for the duration of the test.

We've done lots of other tests, including 0 - 1000 / 2000 over 1, 2, 5 minutes etc.

I've already ported 56e4594 thanks :+1: plus, many many others
Also, we saw large memory usage using GC.

My next step is to look at the latest version of EasyCaching - I believe the nopTeam tried it, but it hit a wall. I also believe they are now looking at LazyCaching too.

For more tests, and details of the server, have a look at #4964 

One thing to add is that the current tests are being performed on a development site, not the live. The last time we pushed the dev to the live, we saw a massive reduction in performance from the dev to live (even though both reside on the same server).

The live, uses a database which, has over time, been upgraded from 3.00, 3.2, 3.7, 4.00, 4.30 - it, as far as I'm aware, was the first, full response, live multi-store.

Increase the app pool worker processes has yielded the biggest performance increase we've seen so far, but until we can solve the issue of the scheduled task, it's a no go.

We're trying awfully hard to keep the client on board, but I feel we're losing the battle with them.

Regards,
Craig

**Comment by untiedshoes** [comment] 2020-12-01 10:11
Update! For now, it looks like I solved the scheduled tasks running more than once when using multiple app pool worker processes.

After some testing, I've not received a single, duplicate order email... I'll continue testing today, and report back this evening.

For anyone wondering:

`private void TimerHandler(object state)
        {
            try
            {
                _timer.Change(-1, -1);
                Run();
            }
            catch
            {
                // ignore
            }
            finally
            {
                if (RunOnlyOnce)
                    Dispose();
                else
                    _timer.Change(Interval, Interval);
            }
        }`

Sorry for going slightly off-topic here :)

**Comment by skoshelev** [comment] 2020-12-21 06:25
Closed #2287. 
You may find all related commits by [this link](https://github.com/nopSolutions/nopCommerce/search?q=2287&type=commits)

**Closed by skoshelev** 2020-12-21 06:25 UTC
Labels: enterprise / highlight feature, refactoring / source code
