### ISSUE TITLE
Unable to Cancel Orders 

### ISSUE THREAD

**Issue by webzest** [nopSolutions/nopCommerce#3621] opened 2019-03-23 12:52 UTC
nopCommerce version: 4.1

Steps to reproduce the problem: 
1. Add Product to Cart and CheckOut to Pay with PayPal
2. Changed my mind and Cancel The order
3.  Returned from Paypal to my Site: Order# is generated and it looks like Order has been processed.  However, I did not pay.  I received an Email thanking me for the Order and the Store Admin also received a completed Order that is ready to be fulfilled.  On the Admin Side of nopCommerce, there is an Order listed as Pending.

So, Essentially, even though I canceled the order and did not Pay, it is still listed as being made.
I think Cancelled Orders should just return to the page and no emails or listings should be posted.  An entry in the Admin side should be recorded as Cancelled so we can contact the Client if we want to, however, if the client did decide later to update her order and completes it, the Cancelled order entry should be removed.

**Comment by AndreiMaz** [comment] 2019-03-23 15:22
Order is generated before you're redirected. It's by design for all "redirection" payment method. It's marked as "Pending" before it's paid

**Closed by AndreiMaz** 2019-03-23 15:22 UTC

**Comment by webzest** [comment] 2019-03-23 15:51
@AndreiMaz ,
Thank you for your response.  if this is not a bug, then I think we can improve the process and update the code to prevent the Emailing to Store and User if the Sale was canceled at the PayPal page.  This would avoid overhead and store confusion since they do not know if the order was paid or failed during the payment process.
