### ISSUE TITLE
PickupInStore localization issues

### ISSUE THREAD

**Issue by jrvidotti** [nopSolutions/nopCommerce#4967] opened 2020-08-04 15:45 UTC
nopCommerce version: 4.30

Steps to reproduce the problem: 

Using Portuguese Brazil localization number format is #.##0,00 

Trying to save latitude and longitude, the plugin don't save in any number format.

If number is "-15.55752600", message error is "Latitude should be in range -90 to 90" when Save is clicked.

If number is "-15,55752600", message error is "The field Latitude must be a number." when text edit lost focus.

![image](https://user-images.githubusercontent.com/5623041/89314617-e159c400-d647-11ea-8249-7089e926a2a3.png)

![image](https://user-images.githubusercontent.com/5623041/89314657-eae32c00-d647-11ea-8b01-a97b7269b628.png)

**Comment by jrvidotti** [comment] 2020-09-09 18:15
> @jrvidotti Please, clarify the literal meaning of the culture you are using?

Hi, @DmitriyKulagin !

I didn't understood your question. Can you please elaborate? 

In portuguese, decimal number is represented with a comma (not a dot), like "1234,56". In english, decimal number is represented with dot (1234.56).

My guess is that nopCommerce localization is not modifying frontend validation, only backend.

To solve the problem, I think frontend validation should accept localized values like "-15,55752600". As backend validation is not accepting number with decimal dot, it should accept with decimal comma.

Am I made myself clear?

**Comment by DmitriyKulagin** [comment] 2020-09-10 07:20
@jrvidotti 
I understand the essence of your problem, but locally I cannot reproduce such an error. Therefore, please clarify what language settings you used - `Language culture` and `Unique SEO code` (Configuration -> Languages -> Edit language details)?

**Comment by landlogicit** [comment] 2020-10-11 17:08
Same problem with Italian language. Language culture it, seo code it. if I am in the admin area and for example I go to the management of measures on dimensions and I modify a value on ratio it is converted badly. if I pass 0,2 it puts 2, if I put 0.2 it always puts 2. this problem does not happen with the English language.

**Comment by DmitriyKulagin** [comment] 2020-10-28 13:47
@jrvidotti  Since we were unable to reproduce the described problem, we do not exclude that other users may also encounter a similar situation. But we want to stop using the kendo library, so this situation should be addressed in issue #5016.

**Closed by DmitriyKulagin** 2020-10-28 13:47 UTC
Labels: discussion / investigation
