### ISSUE TITLE
Microdata is missing important microdata attributes

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/nopCommerce#3682] opened 2019-04-12 01:53 UTC
nopCommerce version: 4.1

Steps to reproduce the problem: 
The following link shows several errors and warning on NopCommerce's public demo page: 
https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fdemo.nopcommerce.com%2Fapple-macbook-pro-13-inch

**Comment by DmitriyKulagin** [comment] 2019-11-22 08:41
Duplicate of this issue #4129

**Closed by DmitriyKulagin** 2019-11-22 08:41 UTC
Labels: refactoring / source code
