### ISSUE TITLE
GDPR and delete account data does not work as expected

### ISSUE THREAD

**Issue by pantonis** [nopSolutions/nopCommerce#3559] opened 2019-02-25 12:46 UTC
nopCommerce version: 4.10

Steps to reproduce the problem: Go to Account/Edit and then click on GDPR => Permanent Delete.
Then I go to database and run the following 

```
SELECT * FROM [dbo].Customer WHERE Id = 1278
SELECT * FROM [dbo].[CustomerAddresses] WHERE Customer_Id = 1278
SELECT * FROM [dbo].CustomerPassword WHERE CustomerId = 1278
SELECT * FROM [dbo].GdprLog WHERE CustomerId = 1278
SELECT * FROM [dbo].[Order] WHERE CustomerId = 1278
SELECT * FROM [dbo].[ShoppingCartItem] WHERE CustomerId = 1278
```
and the data are still there

**Comment by RomanovM** [comment] 2019-03-01 06:38
@pantonis It works as expected - all sensitive customer data is deleted. 1278 is just an id, it doesn't identify a person.

**Comment by pantonis** [comment] 2019-03-01 06:50
@RomanovM 1278 is the client Id whose data were supposed to be deleted from the above tables in the query. All select statements return data

**Comment by cnEUL** [comment] 2019-03-01 10:20
The data of the GDPDR may not be deleted in my opinion so simply. Here the regulations of the tax office are of higher value. In this case, orders and everything that led to this order or invoice may not be deleted.
If within the order therefore an address is referred to, where further information, which are bill-relevant, one must lift these surely.
The log must be kept in any case, because if someone has agreed to something and discards this at any time, a proof is required.
The deletion internally sets a flag, so that this address can no longer be used via standard mechanisms.  Which is to be checked if certain parts of the address are not relevant for billing and that these certain fields can then be deleted.

**Comment by pantonis** [comment] 2019-03-02 09:51
@cnEUL  this is not a discussion for what to delete or not. It is about a bug in the code.

Based on this [code](https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Services/Gdpr/GdprService.cs#L317) 
some of the above data should have been deleted

**Comment by cnEUL** [comment] 2019-03-03 10:12
Nop Commerce only sets the deleted flag when deleting records. You can therefore always select an ID using SQL commands - but as already described above, when deleting data that goes into accounting, it must not disappear, but only be removed from normal access. The log must also be kept. In my opinion this is as it is, ok.

**Comment by pantonis** [comment] 2019-03-03 13:32
@cnEUL As I said this is not a discussion as to whether to keep private data or not. 
It is about code not working. So please do not post again about this topic as the moderators might not see the possible discussed code bug. If you wish you can open another ticket with the topic you want to discuss.

P.S This [link](https://ec.europa.eu/info/law/law-topic/data-protection/reform/rules-business-and-organisations/dealing-citizens/do-we-always-have-delete-personal-data-if-person-asks_en)might help you understand what must be deleted.

**Comment by AndreiMaz** [comment] 2019-03-18 13:46
Customer ID is not a ensitive data as it's internal. All sensitive customer data is deleted

**Comment by pantonis** [comment] 2019-03-19 08:13
@AndreiMaz I tried but all data are not deleted. I can see still address

**Comment by AndreiMaz** [comment] 2019-04-21 05:35
Addresses are deleted. I cannot reproduce it. All addresses are deleted except addresses used to place an order

**Comment by AndreiMaz** [comment] 2019-04-21 05:36
Closing it as it works as expected (cannot reproduce)

**Closed by AndreiMaz** 2019-04-21 05:36 UTC
