### ISSUE TITLE
Error loading BestsellersReportLine on home page (after upgrading)

### ISSUE THREAD

**Issue by haimca** [nopSolutions/nopCommerce#2706] opened 2017-11-01 10:27 UTC
Hi,
After upgrading to latest v4.00 beta I'm getting this error: 

System.InvalidOperationException occurred
**The specified cast from a materialized 'System.Decimal' type to the 'System.Int32' type is not valid.**

It's because the result from this query returns 2 decimal values, and the BestsellersReportLine model is defined as Int, Decimal, Int

![image](https://user-images.githubusercontent.com/4253166/32270735-c953e622-beff-11e7-8570-cab0ec6a797a.png)

![image](https://user-images.githubusercontent.com/4253166/32270771-e7fddda8-beff-11e7-97a1-d0f6212f3f7c.png)

```
public partial class BestsellersReportLine
    {       
        public int ProductId { get; set; }
        public decimal TotalAmount { get; set; }
        public int TotalQuantity { get; set; }
    }
```

**Comment by AndreiMaz** [comment] 2017-11-01 12:19
@haimca 
1. what is your SQL Server version? 
2. I presume you have at least several completed order as you're upgrading. Please confirm
3. Is it possible for you to use SQL Server profiler and see the generated SQL command? 
4. If yes, then please open SQL Server Management Studio and execute this SQL command manually. Please share results here

**Comment by haimca** [comment] 2017-11-01 12:41
1. Microsoft SQL Server 2014 - 12.0.2269.0
2. Yes, there are several orders.
3. Here is the SQL command generated from LINQ in OrderReportService\BestSellersReport:

SELECT 
    [Project3].[ProductId] AS [ProductId], 
    [Project3].[C1] AS [C1], 
    [Project3].[C2] AS [C2]
    FROM ( SELECT 
        [GroupBy3].[A1] AS [C1], 
        [GroupBy3].[A2] AS [C2], 
        [GroupBy3].[K1] AS [ProductId]
        FROM ( SELECT 
            [Project2].[ProductId] AS [K1], 
            SUM([Project2].[PriceExclTax]) AS [A1], 
            SUM([Project2].[Quantity]) AS [A2]
            FROM ( SELECT 
                [Project1].[ProductId] AS [ProductId], 
                [Project1].[Quantity] AS [Quantity], 
                [Project1].[PriceExclTax] AS [PriceExclTax], 
                [Project1].[StoreId] AS [StoreId], 
                [Project1].[OrderStatusId] AS [OrderStatusId], 
                [Project1].[ShippingStatusId] AS [ShippingStatusId], 
                [Project1].[PaymentStatusId] AS [PaymentStatusId], 
                [Project1].[Deleted] AS [Deleted], 
                [Project1].[CreatedOnUtc] AS [CreatedOnUtc], 
                [Project1].[VendorId] AS [VendorId], 
                [Project1].[Published] AS [Published], 
                [Project1].[Deleted1] AS [Deleted1], 
                [Project1].[CountryId] AS [CountryId], 
                [Project1].[C1] AS [C1], 
                (SELECT 
                    COUNT(1) AS [A1]
                    FROM [dbo].[Product_Manufacturer_Mapping] AS [Extent6]
                    WHERE ([Project1].[Id] = [Extent6].[ProductId]) AND ([Extent6].[ManufacturerId] = @p__linq__17)) AS [C2]
                FROM ( SELECT 
                    [Extent1].[ProductId] AS [ProductId], 
                    [Extent1].[Quantity] AS [Quantity], 
                    [Extent1].[PriceExclTax] AS [PriceExclTax], 
                    [Extent2].[StoreId] AS [StoreId], 
                    [Extent2].[OrderStatusId] AS [OrderStatusId], 
                    [Extent2].[ShippingStatusId] AS [ShippingStatusId], 
                    [Extent2].[PaymentStatusId] AS [PaymentStatusId], 
                    [Extent2].[Deleted] AS [Deleted], 
                    [Extent2].[CreatedOnUtc] AS [CreatedOnUtc], 
                    [Extent3].[Id] AS [Id], 
                    [Extent3].[VendorId] AS [VendorId], 
                    [Extent3].[Published] AS [Published], 
                    [Extent3].[Deleted] AS [Deleted1], 
                    [Extent4].[CountryId] AS [CountryId], 
                    (SELECT 
                        COUNT(1) AS [A1]
                        FROM [dbo].[Product_Category_Mapping] AS [Extent5]
                        WHERE ([Extent3].[Id] = [Extent5].[ProductId]) AND ([Extent5].[CategoryId] = @p__linq__15)) AS [C1]
                    FROM    [dbo].[OrderItem] AS [Extent1]
                    INNER JOIN [dbo].[Order] AS [Extent2] ON [Extent1].[OrderId] = [Extent2].[Id]
                    INNER JOIN [dbo].[Product] AS [Extent3] ON [Extent1].[ProductId] = [Extent3].[Id]
                    INNER JOIN [dbo].[Address] AS [Extent4] ON [Extent2].[BillingAddressId] = [Extent4].[Id]
                )  AS [Project1]
            )  AS [Project2]
            WHERE (@p__linq__0 = 0 OR @p__linq__1 = [Project2].[StoreId]) AND ((@p__linq__2 IS NULL) OR (@p__linq__3 <= [Project2].[CreatedOnUtc])) AND ((@p__linq__4 IS NULL) OR (@p__linq__5 >= [Project2].[CreatedOnUtc])) AND (@p__linq__6 IS NULL OR @p__linq__7 = [Project2].[OrderStatusId]) AND (@p__linq__8 IS NULL OR @p__linq__9 = [Project2].[PaymentStatusId]) AND (@p__linq__10 IS NULL OR @p__linq__11 = [Project2].[ShippingStatusId]) AND ([Project2].[Deleted] <> 1) AND ([Project2].[Deleted1] <> 1) AND (@p__linq__12 = 0 OR [Project2].[VendorId] = @p__linq__13) AND ((0 = @p__linq__14) OR ([Project2].[C1] > 0)) AND ((0 = @p__linq__16) OR ([Project2].[C2] > 0)) AND (@p__linq__18 = 0 OR [Project2].[CountryId] = @p__linq__19) AND (@p__linq__20 = 1 OR [Project2].[Published] = 1)
            GROUP BY [Project2].[ProductId]
        )  AS [GroupBy3]
    )  AS [Project3]
    ORDER BY [Project3].[C2] DESC


4. Here are the results:

![image](https://user-images.githubusercontent.com/4253166/32275079-821edb0a-bf12-11e7-869d-9d638898d916.png)

**Comment by AndreiMaz** [comment] 2017-11-01 13:32
@haimca What is the type of "Quantity" column of "Order" table (in database, not in source code)?

**Comment by haimca** [comment] 2017-11-01 13:42
It's decimal
![image](https://user-images.githubusercontent.com/4253166/32277445-2879965e-bf1b-11e7-8c93-22efeb4af9d6.png)

Should it be integer ?

**Comment by AndreiMaz** [comment] 2017-11-01 14:30
@haimca yes. It's "int" by default. So the issue is caused by your customization. Please update (just find out why it was done)

closing this issue...

**Closed by AndreiMaz** 2017-11-01 14:30 UTC
Labels: discussion / investigation / rfc
