### ISSUE TITLE
Better theme management similar to local plugins

### ISSUE THREAD

**Issue by atulrungta** [nopSolutions/nopCommerce#7072] opened 2024-02-15 08:46 UTC
nopCommerce version: 4.60
Steps to reproduce the problem: When you upload a newer version of same theme which exists already in the nopCommerce installation, you get a message, "A theme with '{themeDescriptor.SystemName}' system name is already defined".

The problem we faced here is, the theme has no versioning similar to plugins and if there is an update in the theme for the same nopCommerce version, we are not able to upload theme from the admin interface from where we upload a new version of plugins.

There is also one more concern that a store owner or someone who's managing admin, isn't able to manage themes. Such as deleting a theme which is no longer in use because there is no interface for the same.

I suggest that we should have a version field in theme.json similar to what we have in plugin.json and during upload, if the version is newer then replace the theme instead of giving this error message.

I figured out that this error is thrown from the method "GetThemeDescriptorFromText" under ThemeProvider.cs class.

**Comment by RomanovM** [comment] 2024-02-16 03:29
Duplicate of #5744

**Closed** 2024-02-16 03:38 UTC
