### ISSUE TITLE
Back in stock notifications for attribute combinations

### ISSUE THREAD

**Issue by Manuel-Innovapps** [nopSolutions/nopCommerce#7396] opened 2024-11-05 09:44 UTC
nopCommerce version: 4.70.x

Steps to reproduce the problem: 
Back in stock notifications currently only work when "ManageStock" is selected. They should also work when "ManageStockByAttributes" is selected. This would also require changes in the frontend.

**Comment by RomanovM** [comment] 2024-12-11 12:22
Duplicate of #1690

**Closed** 2024-12-11 12:22 UTC
Labels: discussion / investigation
