### ISSUE TITLE
At least 3 bugs in adding a new customer when logged in as an administrator.

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/nopCommerce#3381] opened 2018-10-18 04:39 UTC
nopCommerce version: 
4.1

System hardware and Software:
iPad Gen 4
Chrome version latest

Steps to reproduce the problem: 
1. Ensure you have the admin@yourstore.com account username and password saved in chrome autofill
2. Login into site as admin@yourstore.com.  Autofill should automatically fill in username and passwoed.
3. Go to customer page and add new customer.  Note the admin@yourstore.com and password are automatically filled in. Bug 1
4. Overwrite the username and password with a new email "new@yourstore.com" and make a new password.  Add administrator role and save.
5. Edit "new@yourstore.com" customer again. Note Bug 1 again.
6.  Overwrite the username and password with "new@yourstore.com" with the same password.  Click delete.  Delete should be successful.
7. Repeat step 3 through 4.  Note it says "new@yourstore.com" is already registered, but it was previously deleted. Bug 2
8. Go back to customer screen.  The new customer isn't listed.  Orphaned record? Bug 3.

I'm unsure whether Autofill (password lock) is creating this issue or nopcommerce is creating it. I suspect NopCommerce is filling the username and password with the logged in user. This may work fine as a customer, but not as an administrator.

**Comment by RomanovM** [comment] 2018-10-24 07:42
Thanks. 1 - It's not because of nop, it's the 'autofill' function of your browser. 2 - it's by design, customer is marked as deleted, but not deleted completely, therefore such an error message is displayed. 3 - related with 2. 
So, there are no bugs with customer workflow, I close this task.

**Closed** 2018-10-24 07:43 UTC

**Comment by toddca** [comment] 2018-10-24 12:10
What a pay to punt this one - there is no need to allow the browser to autofill a username and password on the page which an admin creates a new user, nop should turn this off using attributes on those input elements. So rather than just saying there are no bugs please try to understand the problem and how you can correct it than just saying its the browser as if there is not an option to control the browser behaviour here.

**Comment by Joebeazelman** [comment] 2018-10-24 23:05
@toddca  LOL!  That was more like having the football yanked just before your foot makes contact and landing on your arse in a violent manner,
