### ISSUE TITLE
Match URL path and breadcrumbs on a product page when "Product URL structure type" is Category

### ISSUE THREAD

**Issue by SagarKayastha** [nopSolutions/nopCommerce#6476] opened 2022-12-21 09:31 UTC
nopCommerce version: 4.60

Steps to reproduce the problem: 
Step 1: Redirect on Admin panel > Configuration > Settings > Catalog setting > Product page tab > Product URL structure type as (/category/product) 
Step 2: Create 1 product from admin side
Step 3: Add multiple category from this product from admin side.
Step 4: Save product and redirect on public side
Step 5: Open Configured product from any category
Step 6: Observe that Slug and Breadcrumb is not showing proper

 

Expected result: Slug and Breadcrumb should show proper
 Please refer attachment
![Slug_breadcrumb ](https://user-images.githubusercontent.com/82799708/208871616-33235f3f-bdf9-4500-8485-d2de8035a472.png)

**Comment by skoshelev** [comment] 2022-12-21 10:18
Duplicate of #5776

**Closed** 2023-01-10 08:35 UTC
Labels: refactoring / source code
