### ISSUE TITLE
Delete guest task connection leak on PostgreSQL

### ISSUE THREAD

**Issue by mmurari-alfa** [nopSolutions/nopCommerce#5638] opened 2021-04-23 08:56 UTC
We have found that the task for removing guests is faulty and leaves an open connection on the database each time is executed.
After a while the connection pool get's full and nopcommerce crashes.

We are using nopcommerce 4.40.2, OS: Unix 4.18.0.193, DB: PostgreSQL12.3  

Below a screenshot of the pgadmin console.. 

![screenshot](https://user-images.githubusercontent.com/83063663/115845863-9b38d080-a421-11eb-9d53-99c9ca38cf0a.png)

.

**Comment by RomanovM** [comment] 2021-04-23 09:16
Duplicate of #5556

**Closed** 2021-04-23 09:16 UTC
