### ISSUE TITLE
get the error message when i try to open /Admin/Plugin/List

### ISSUE THREAD

**Issue by isbappa** [nopSolutions/nopCommerce#3829] opened 2019-05-13 08:47 UTC
nopCommerce version: 4.1

Steps to reproduce the problem: 

An unhandled exception occurred while processing the request.WebException: The remote server returned an error: (404) Not Found.Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions+<>c.<UseNopExceptionHandler>b__1_1(HttpContext context) in ApplicationBuilderExtensions.cs, line 83my website hosted on azure.I have used many of plugin.please help me to solve this error message.https://ibb.co/SyJYM4Mhttps://ibb.co/qNgpf3V
--

**Comment by RomanovM** [comment] 2019-05-13 13:30
duplicate of https://github.com/nopSolutions/nopCommerce/issues/3182

**Closed** 2019-05-13 13:30 UTC
