### ISSUE TITLE
Payment method design issue

### ISSUE THREAD

**Issue by ecommerce-tester** [nopSolutions/nopCommerce#4488] opened 2020-04-06 10:39 UTC
nopCommerce version: 4.30 beta
 
![er](https://user-images.githubusercontent.com/43282933/78550054-783a7f00-7814-11ea-9031-5b7423ecfa06.png)

**Comment by AndreiMaz** [comment] 2020-04-06 11:46
@ecommerce-tester I cannot reproduce the issue. 
1. What is your screen resolution? 
2. What browser are you using?
3. Do you experience it only on this page?

**Comment by ecommerce-tester** [comment] 2020-04-06 12:14
1.1366x768
2.Google chrome 80.0.3987.162
3.Yes
Fixing when i click update grid.

**Comment by MafdyAzer** [comment] 2020-05-07 10:57
![image](https://user-images.githubusercontent.com/57217759/81286664-b1f3e500-9061-11ea-800b-b243b76c3cb7.png)


This error exist in nopCommerce version: 4.20 (Latest release) Also.

I think it because of the logo dimensions, as if I uploaded a small one, will be fixed.

**Comment by holydk** [comment] 2020-05-13 11:29
Closed #4488

**Closed by holydk** 2020-05-13 11:29 UTC
Labels: bug

**Comment by ecommerce-tester** [comment] 2020-05-13 13:52
@holydk @AndreiMaz 
it's not a good idea, i meen "no logo no problem" .
