### ISSUE TITLE
nopCommerce 4.10 - Plugin un-installed and called in plugin service.

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#3502] opened 2019-01-15 07:40 UTC
nopCommerce version: 4.10

 override few nopCommerce default service in my plugin.
My plugin is un-installed.

1. On application restart, I get debug point on un-installed plugin's DependencyRegister.cs file and it register all my overrided services. 

2. When checking nopCommerce existing functionality, it's calling in overrided service even my plugin is un-installed.
This post/answer is useful
0
This post/answer is not useful

**Steps to reproduce the problem:** 

- Un install any existing plugin which have dependency register file
- Add debug point in dependency register file
- Restart application, you will get debug point on dependency register file.
This should be not happen as plugin is uninstalled.

[Here](https://www.nopcommerce.com/boards/t/57718/nopcommerce-410-plugin-un-installed-and-called-in-plugin-service.aspx) I create forum post.

**Comment by Xzelsius** [comment] 2019-01-15 14:53
We solved this problem using a one-liner

`if (PluginManager.ReferencedPlugins?.SingleOrDefault(p => p.Installed && p.SystemName == "PLUGIN-NAME") == null) return;`

**Comment by RomanovM** [comment] 2019-01-15 15:02
Duplicate of https://github.com/nopSolutions/nopCommerce/issues/471

**Closed** 2019-01-15 15:02 UTC
