### ISSUE TITLE
Translation of Message templates and Topics by importing language resources (contribution)

### ISSUE THREAD

**Issue by cnEUL** [nopSolutions/nopCommerce#3862] opened 2019-05-18 06:43 UTC
nopCommerce version: 4.20

Steps to reproduce the problem: 
i have made the translation of the message templates and also of the topics from new installation of nop in a similar format like the string resources.
Actually i handle it with a script directly on the host machine to import those after a new installation. But not everyone has the possibility to get the rights to do so.
So it would be a good help for others, to enhnace the language import (by an optional identifier) to import also message templates and topics in other languages. i am shure, that would help much the peaple for setting up a localized nopCommerce shop. We have made translations in german and italien languages in he attached format for lot of nopCommerce versions.

For identifing body, subject we have used the origin field name, which enhances the internal name.
example: <LanguageResource Name="CheckoutAsGuestOrRegister.Body" Id="2">

Attached the two xml files.

[TemplateResource.zip](https://github.com/nopSolutions/nopCommerce/files/3193750/TemplateResource.zip)

**Comment by RomanovM** [comment] 2019-06-19 13:58
duplicate of https://github.com/nopSolutions/nopCommerce/issues/1891

**Closed by RomanovM** 2019-06-19 13:58 UTC
Labels: functionality / feature
