### ISSUE TITLE
4.30 - Edit Order Totals go to $0.00

### ISSUE THREAD

**Issue by Ochapparel** [nopSolutions/nopCommerce#4462] opened 2020-04-03 12:54 UTC
nopCommerce version: 
4.30

Steps to reproduce the problem: 
1) **Open** an **order**
2) Hit **Edit order totals**
3) Increment **excl tax:**
4) Hit **Save order Totals**
5) It all goes to $0.00

![image](https://user-images.githubusercontent.com/20989983/78362661-7c526c80-7588-11ea-8e9d-cdd7aedbd4ed.png)

![image](https://user-images.githubusercontent.com/20989983/78362698-8b391f00-7588-11ea-8b27-dae743d434c9.png)

![image](https://user-images.githubusercontent.com/20989983/78362759-a3a93980-7588-11ea-9b30-afc67c3013ee.png)

![image](https://user-images.githubusercontent.com/20989983/78362771-a9068400-7588-11ea-9ce5-3b4cc62c1246.png)

**Comment by skoshelev** [comment] 2020-04-03 13:11
Hi @Ochapparel. Thank you, but duplicate of #4396

**Closed by skoshelev** 2020-04-03 13:11 UTC
