### ISSUE TITLE
NopCommerce doesn't properly check for versioning

### ISSUE THREAD

**Issue by Joebeazelman** [nopSolutions/nopCommerce#3326] opened 2018-09-24 19:24 UTC
I discovered during development that it's possible to have versioning problems.  Under certain circumstances, stale DLLs can cause certain operations to fail.  In particular, I discovered NopCommerce 4.1 went through the process of installing my plugin, but there were no errors or signs the plugin was loaded.  Deleting the cache and restarting the site didn't help.  For some odd reason, the plugins were able to load without any issues.

I suspect I build a 4.2 version ran it and installed the plugins, but when I went back to 4.1 some stale DLLs may have been loaded.  Since all the plugins were versioned correctly, perhaps the code responsible for loading the DLLs in the Admin loaded the DLL, but the other parts of nop couldn't detect it.

nopCommerce version: 
4.1 beta up

Steps to reproduce the problem:

**Comment by AndreiMaz** [comment] 2018-09-24 19:31
Could you please provide a complete list of steps to reproduce the issue?

nopCommerce properly checks and compares the current version. Please see https://github.com/nopSolutions/nopCommerce/blob/develop/src/Libraries/Nop.Core/Plugins/PluginManager.cs#L436

**Comment by Joebeazelman** [comment] 2018-09-24 22:01
Thanks for getting back to me.  I can only tell you what I did, but I'm not so sure you'll have the same experience.  I thought the problem went away, but it returned.  It turns out it may have nothing to do with versioning, but it would be nice if Nop told me I had incorrect plugin versions earlier, instead of an empty list of plugins.

I am running the site using visual studio running from IIS Express.  When I install a plugin, it goes through the motions of installation, but it never actually loads.  The Install and delete still appear and none of the Plugin screens are available.  The file containing the list of installed plugins is updated but none of the functionality of the plugins are loaded.  Clearing the cache and restarting the application has no effect.  

I discovered that I can get the plugins to load by restarting the IIS Express process.  Stopping the debugger from Visual Studio doesn't kill it as it continues to live on.  I suspect the problem has to do with caching.  I noticed NopCommerce loads the plugins in memory.  Without knowing the details, perhaps .NET core is a bit more aggressive with its caching.  Perhaps there's a something going on between Kestrel and IIS?

**Comment by AndreiMaz** [comment] 2018-09-25 05:03
" would be nice if Nop told me I had incorrect plugin versions earlier, instead of an empty list of plugins." - actually this warning is displayed in admin area > system > warnings

I think we can close this issue as it works fine. We cannot reproduce it.

**Closed by AndreiMaz** 2018-09-25 05:03 UTC

**Comment by Joebeazelman** [comment] 2018-09-25 19:13
plugins." - actually this warning is displayed in admin area > system > warnings

Yes, I'm sure it does, but to someone who just installed it, wouldn't it be far more informative if instead of displaying a blank plugins list,  it listed them like this:

Fedex Plugin        Error, incompatible plugin version [delete]
Ups Plugin            Error, Incompatible plugin version [delete]
USPS Plugin         Error, Incompatible plugin version [delete]

The warnings can be easily overlooked because they are often ignored for a variety of reasons, including the user thinking that an incompatible plugin should be an error instead of a warning.  It also gives the user the opportunity to cleanup their plugins folder.
