### ISSUE TITLE
Marking reviews as not/helpful doesn't work

### ISSUE THREAD

**Issue by professor-k** [nopSolutions/nopCommerce#6251] opened 2022-04-28 19:42 UTC
nopCommerce version: 4.50.1

Steps to reproduce the problem: 
Find any product with review, click "thumb up".

Messagebox will show up saying "Failed to vote. Please refresh the page and try one more time.".

Under the hood POST to ~/setproductreviewhelpfulness fails with error 400. It looks like it requires antiforgery token.

**Comment by glhays** [comment] 2022-04-29 02:57
I think this may be related to previous issue #6165 that was fixed in the last minor release.
I had similar issue with other files.

________________________________
From: Andriy Kvasnytsya ***@***.***>
Sent: Thursday, April 28, 2022 12:43:40 PM
To: nopSolutions/nopCommerce ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nopSolutions/nopCommerce] Marking reviews as not/helpful doesn't work (Issue #6251)


nopCommerce version: 4.50.1

Steps to reproduce the problem:
Find any product with review, click "thumb up".

Messagebox will show up saying "Failed to vote. Please refresh the page and try one more time.".

Under the hood POST to ~/setproductreviewhelpfulness fails with error 400. It looks like it requires antiforgery token.

**Comment by RomanovM** [comment] 2022-04-29 09:30
Duplicate of #6165

**Closed by RomanovM** 2022-04-29 09:30 UTC
Labels: discussion / investigation

**Comment by professor-k** [comment] 2022-04-29 13:10
Oh. Sorry. There already is 4.50.2. Totally missed that. You guys got pretty good release tempo with 4.50, keep up the good work!
