### ISSUE TITLE
nopCommerce 4.5 Sort Filter by A to Z and Z to A is not working

### ISSUE THREAD

**Issue by rajupaladiya** [nopSolutions/nopCommerce#6200] opened 2022-03-24 04:51 UTC
nopCommerce version: 4.5

Steps to reproduce the problem: 
Go Notebook category page on demo - https://demo.nopcommerce.com/notebooks
Try to filter by A to Z and Z to A.
It is not working, rest of are working fine

**Comment by skoshelev** [comment] 2022-03-24 07:04
Duplicate of #6150

**Closed by skoshelev** 2022-03-24 07:04 UTC
Labels: discussion / investigation
