### ISSUE TITLE
Poor performance due to thousands of queries for DiscountRequirement from the database

### ISSUE THREAD

**Issue by BeniFreitag** [nopSolutions/nopCommerce#6951] opened 2023-12-12 10:47 UTC
nopCommerce version: 4.60.5

**Steps to reproduce the problem:** 
1. Create 3 categories
2. Create 20 products, assign each product to these categories
3. Create 1 discount, Assigned to categories, assign the 3 categories, add at least one **Discount Requirement** (e.g. _Must be assigned to customer role_)
4. Configure the category to show 20 products
5. Open _SQL Server Profile_ to trace the Database Queries
6. Open the category page
7. Check _SQL Server Profiler_, you'll see about 120 SELECT-Queries to _DiscountRequirement_ which are mostly identically.

**Real Use Case**
We have nopCommerce 4.60.5 in production with 40 Discount Rules (various reseller discounts, each having a DiscountRequirement for the User-Role) and 40 Products shown per Page. This results in between 3'000 and 5'400 Database-Queries to DiscountRequirement and a Page Load-Time between 2 and 5.5 seconds. When I set the Discounts to inactive, performance is great (200ms to 400ms). In nopCommerce 4.20 we didn't have this issue.

**Debbuging Information**
The queries seem to be made by `Nop.Services.Discounts.DiscountService.GetDiscountRequirementsByParentAsync()` called by
- `Nop.Services.Discounts.DiscountService.GetValidationResultAsync()`
- `Nop.Services.Discounts.DiscountService.ValidateDiscountAsync()`
- `Nop.Services.Catalog.PriceCalculationService.GetAllowedDiscountsAppliedToCategoriesAsync()`
- `Nop.Services.Catalog.PriceCalculationService.GetAllowedDiscountsAsync()`
- `Nop.Services.Catalog.PriceCalculationService.GetDiscountAmountAsync()`
- `Nop.Services.Catalog.PriceCalculationService.GetFinalPriceAsync()`
- `Nop.Services.Catalog.PriceCalculationService.GetFinalPriceAsync()`
- `Nop.Web.Factories.ProductModelFactory.PrepareSimpleProductOverviewPriceModelAsync()`
- `Nop.Web.Factories.ProductModelFactory.PrepareProductOverviewPriceModelAsync()`
- `Nop.Web.Factories.ProductModelFactory.PrepareProductOverviewModelsAsync()`
- ...

Seems to be a caching issue. The result from GetDiscountRequirementsByParentAsync() should be cached.

**Comment by skoshelev** [comment] 2023-12-12 11:57
Hi @BeniFreitag. thank you for your research and proposed solution, we have already solved this problem as part of ticket #6892

Duplicate of #6892

**Closed by skoshelev** 2023-12-12 11:57 UTC
Labels: discussion / investigation
