### ISSUE TITLE
Making the combination attribute to be disabled when stock is 0

### ISSUE THREAD

**Issue by ahmadkq** [nopSolutions/nopCommerce#5071] opened 2020-10-06 07:48 UTC
nopCommerce version: 4.20

Steps to reproduce the problem: 

1- Have a product with size (L, M, S) and colors (Red, Green, Blue) attributes.
2- Have all attribute combination.
3- Some combinations are 0 stock.
4- The customer will click on a color, the size with that color should be disabled.

We may need to have an option to specify the main attribute. For example if the color is the main attribute, then select a color the size will be disabled based on the stocks quantity.

**Comment by holydk** [comment] 2020-11-02 13:17
Duplicate of #2909 . We are already working on a solution.

**Closed by holydk** 2020-11-02 13:17 UTC
Labels: discussion / investigation
