### ISSUE TITLE
Plugin configuration page fails to load if UsePluginsShadowCopy is set to false in appsettings.json

### ISSUE THREAD

**Issue by MCord** [nopSolutions/nopCommerce#3599] opened 2019-03-16 18:16 UTC
nopCommerce version: 4.10

Steps to reproduce the problem: 

1. Set UsePluginsShadowCopy to false in appsettings.json
1. Restart the web server
1. Go to plugins page and try to configure any bundled plugin like `Pickup.PickupInStore` 

You will see an error page telling you 'Nop' namespace does not contain a 'Plugins' namespace.

The root cause seems to be related to the fact that the new plugin management system does not Resolve plugin assemblies if shadow copy is disabled.

**Comment by skoshelev** [comment] 2019-03-18 07:28
Duplicate of https://github.com/nopSolutions/nopCommerce/issues/3489

**Closed by skoshelev** 2019-03-18 07:28 UTC
Labels: discussion / investigation
