### ISSUE TITLE
Blank Category Images

### ISSUE THREAD

**Issue by cklenk** [nopSolutions/nopCommerce#2939] opened 2018-03-29 20:49 UTC
nopCommerce version: 3.9

I am noticing issues with the category images not being displayed. I have looked into the DNS caching issue and the website does not have multiple DNS records. Also, the image itself is not being rendered to the dom. Here is a snip-it.

`<div class="sub-category-item">
                                <h2 class="title">
                                    <a href="/wyndscent-refills">
                                        Wyndscent Refills
                                    </a>
                                </h2>
                                <div class="picture">
                                    <a href="/wyndscent-refills">
                                        <img>
                                    </a>
                                </div>
                            </div>`

It's very hit or miss, the thumbnail images are in the content/images folder and it varies from browser to browser too. If we refresh the browser a few times the images then decide to show up. Or if we refresh the site cache. Does anyone have a fix?

Thanks

**Comment by AndreiMaz** [comment] 2018-03-30 04:46
Please provide a complete list of steps to reproduce the issue

**Comment by cklenk** [comment] 2018-03-30 13:50
Sure thing,

We go to admin => catalog => categories => edit a category => upload a picture. The picture appears for that category for awhile. Then come back after a few hours and the image is totally missing from the dom. That is that snip-it above that I pasted. It's not a broken reference or anything, it's just totally gone from the dom.

Thanks

**Comment by cklenk** [comment] 2018-03-30 14:27
I also forgot to mention that these are sub categories.

**Comment by AndreiMaz** [comment] 2018-03-31 06:02
It works fine for thousands of sites. We cannot reproduce it

What is your site URL?

**Comment by cklenk** [comment] 2018-04-02 13:38
The url is http://wyndscent.kdatasystems.net/scents. We have done a dozen or so Nop sites and this is the first one that has done this. 

Thanks

**Comment by cklenk** [comment] 2018-04-02 14:02
We can also get you admin access if you want that too.

Thanks

**Comment by AndreiMaz** [comment] 2018-04-25 07:26
It looks like someone deleted generated thumbs. Or IIS doesn't have access to files.

we close this issue so it works fine out of the box

**Closed by AndreiMaz** 2018-04-25 07:26 UTC

**Comment by cklenk** [comment] 2018-11-12 20:56
@AndreiMaz this issue is rearing it's ugly head again. We upgraded the store to 4.1 and this issue is still there. The generated thumbnails are there, I can go to the file structure on the server and see them there. And if it was an IIS issue why would only these images not work and not all of them? If we clear the store cache then they come back again. Here is an updated link: 

https://www.wyndscent.com/scents

Thanks
